### ISSUE TITLE
Kodi v17.6 - Erreur d'installation

### ISSUE THREAD

**Issue by microcontroleur** [anisite/DepotQuebec#10]
Lorsque j'installe le Repo sur Kodi 17.6, je reçois l'erreur suivante dans le log de Kodi:

ERROR: Failed to read 'zip://P%3a%5cKodi%5cDepotQuebec-master.zip/DepotQuebec-master/addon.xml'

J'ai tenté ma chance avec Kodi 17.4 et 17.5 également.

**Comment by marseneault** [comment]
Le lien pour telecharger le dépôt est dans le readme.md:  https://github.com/dualB/DepotQuebec/blob/master/repository.depot.quebec/repository.depot.quebec-1.0.0.zip?raw=true

Tu devrais réussir à l'installer de cette façon.

**Comment by microcontroleur** [comment]
Suoer! Ca fonctionne.  Merci.
