### ISSUE TITLE
Noovo non fonctionnel

### ISSUE THREAD

**Issue by erikatremblay** [anisite/DepotQuebec#100]
Bon donc ce soir j’arrive pour ouvrir Noovo.. lui non plus ne fonctionne plus! 🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️ je ne sais pas ce qu’il se passe mais j’ai l’impression que tout le add on complet meurt!! 

Moi j’adore ses applications c’est la vie dans kodi… pas d’annonce a avancer et autres quelqu’un peut aider car là plus grand chose fonctionne 😭 j’ai kodi 20.5. Sur android tv!  Noovo fonctionnait très bien hier mais aujourd’hui il n'ouvre plus du tout!

**Comment by anisite** [comment]
Ça arrive à tous les ans pour la rentrée télévisuelle les api sont mises à jour. J'ai pas encore eu le temps de regarder, ça va venir

**Comment by KodiTopQuebec** [comment]
pour noovo si tu avais fait des raccourcies dans kodi ca fonctionne , mais si l on clique direct sur le addon  , erreur ,

**Comment by KodiTopQuebec** [comment]
noovo depuis quelques jours est revenu par magie (sans mise a jour)

**Comment by anisite** [comment]
c'est vrai @erikatremblay  ?

**Comment by erikatremblay** [comment]
Non il avait arreter de fonctionner mais a recommencer a fonctionner

**Comment by anisite** [comment]
ok je ferme pour le moment, no verra si ça reviens ... merci
