### ISSUE TITLE
ONF / NFB

### ISSUE THREAD

**Issue by esenterre** [anisite/DepotQuebec#11]
Salut, je me demandais si il serait pertinent (à mon avis, oui) d'ajouter le plugin de l'ONF (Office National du Film) au Dépôt Québec. Il y a plein de contenu en français (et en anglais). Le plugin n'est pas tellement mis-à-jour,  mais il est totalement fonctionnel.

https://github.com/newatv2user/plugin.video.nfbca

**Comment by dualB** [comment]
Bonjour! Le dépôt s'est donné comme mission de couvrir les chaînes de télévision francophones du Canada. De plus, les développeurs des additiels que nous offrons sont tous impliqués dans la gestion du dépôt, ce qui nous permet de s'assurer que tous nos additiels sont mis à jour et entretenu au quotidien. Cela nous permet d'offrir un dépôt de qualité, surtout avec le temps bénévole qu'il nous est possible de fournir individuellement! Bref, nous ne souhaitons pas devenir un dépôt de sources tiers. Merci!

**Comment by esenterre** [comment]
Excellente réponse! Merci de votre implication! 👍
