### ISSUE TITLE
TVA

### ISSUE THREAD

**Issue by johnboisvert** [anisite/DepotQuebec#12]
Bonjour,
j'ai réussit a tous installer du dépot, toutv, tv5 etc...
je n'arrive pas a installer TVA il veut rien savoir .. ya t-il un truc?

je roule sur Android 16.1

Merci pour vos addons c'est malade !!

**Comment by MaximeLussier** [comment]
Bonjour,

Comme écris ici: https://plus.google.com/u/0/110820321790708463526/posts/XDi1iNiFWnh?cfem=1
L'Add-On TVA n'est supporté qu'à partir de Kodi 17 dù à TLS 1.2 qui est requis par le site de TVA... Il n'y a pas de façon de contourner ça.

**Comment by johnboisvert** [comment]
ouff ok et kodi 17 pour le modifier va mal pour moi mais merci je vais trouver une solution merci pour votre travail

**Comment by MaximeLussier** [comment]
C'est en effet le problème des boites Android.
