### ISSUE TITLE
Noovo

### ISSUE THREAD

**Issue by johnboisvert** [anisite/DepotQuebec#13]
Bonjour
Tous d'abort merci pour cette magnifique addictiel !!!
Petite question
avant hier quand je cliquais sur une emission sur Noovo l'émission partais normalement
maintenant depuis hier soir quand je clique sur un emission plus rien ce passe rien ouvre 
savez vous pourquoi? svp

**Comment by anisite** [comment]
Non je ne sais pas pourquoi mais merci de m'en informer je vais regarder si quoi que ce soit a changé depuis hier sur leur site ou si c'est simplement une panne de leur service hier

**Comment by johnboisvert** [comment]
J'ai essayer aussi ce matin et meme chose 
tien moi au courrant si ca fais ca pour toi aussi svp :) c'est gentil et lâche pas c'est super !!

**Comment by anisite** [comment]
Avec la vie très mouvementée, je vais tout faire pour que ce soit réglé pour la fin de semaine.

**Comment by anisite** [comment]
Le problème vient du fait que Noovo ont fermé la source des vidéos "mobiles" et l'application simulait être un mobile, je vais devoir réécrire la lecture des sources video

**Comment by anisite** [comment]
@johnboisvert Une correction est en cours de déploiement : la version 0.5.4.
Ça devrait corriger le problème que NOOVO a créé ;-)
Si tu est curieux le changement dans le code ressemble à ça : [https://github.com/anisite/plugin.video.vtele/commit/0c456560fee20062aee06fedaf0a1e7ee28a5710](https://github.com/anisite/plugin.video.vtele/commit/0c456560fee20062aee06fedaf0a1e7ee28a5710)
SVP, m'aviser si le problème est résolut ou non de ton côté!

**Comment by johnboisvert** [comment]
Merci ce midi je test et vous le fais savoir :)

**Comment by johnboisvert** [comment]
Les image des emissions sont revenu mais lorsque je clique sur une emission ca load et rien embarque :(

**Comment by anisite** [comment]
Peux tu vérifier que tu as la mise à jour

Le ven. 11 mai 2018 12 h 21, johnboisvert <notifications@github.com> a
écrit :

**Comment by johnboisvert** [comment]
Oh tous fonctionne merci :dancing_men:
