### ISSUE TITLE
tou.tv ne fonctionne pas pour les films

### ISSUE THREAD

**Issue by ehoffman2** [anisite/DepotQuebec#14]
tou.tv version 2.0.8

Il semble que pour tout ce qui n'a pas d'épisodes, ça ne fonctionne pas.  Autrement dit, ça fonctionne bien pour les séries, mais pas pour les films, documentaires, etc.  En gros, c'est principalement les contenus payant, mais un film qui n'est pas payant (pas 'Extra'), pour essayer, est 'Alter ego'.

Le log me dis ceci:

```
10:54:25.929 T:9492   ERROR: Traceback (most recent call last):
10:54:25.929 T:9492   ERROR:   File "C:\Users\Eric\AppData\Roaming\Kodi\addons\plugin.infologique.tou.tv\resources\lib\toutv.py", line 314, in __init__
10:54:25.930 T:9492   ERROR:     try: player.playVideoExtra( self.args.PIDEXTRA, self.args.KEY, startoffset=self.args.starttime )
10:54:25.930 T:9492   ERROR:   File "C:\Users\Eric\AppData\Roaming\Kodi\addons\plugin.infologique.tou.tv\resources\lib\TouTvPlayer.py", line 91, in playVideoExtra
10:54:25.930 T:9492   ERROR:     data = getVideoExtra( PID )
10:54:25.930 T:9492   ERROR:   File "C:\Users\Eric\AppData\Roaming\Kodi\addons\plugin.infologique.tou.tv\resources\lib\scraper.py", line 23, in getVideoExtra
10:54:25.930 T:9492   ERROR:     emission = json.loads(emission)
10:54:25.930 T:9492   ERROR:   File "C:\Winappl\Multimedia\Kodi\system\python\Lib\json\__init__.py", line 339, in loads
10:54:25.931 T:9492   ERROR:     return _default_decoder.decode(s)
10:54:25.931 T:9492   ERROR:   File "C:\Winappl\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
10:54:25.931 T:9492   ERROR:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
10:54:25.931 T:9492   ERROR:   File "C:\Winappl\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
10:54:25.931 T:9492   ERROR:     raise ValueError("No JSON object could be decoded")
10:54:25.931 T:9492   ERROR: ValueError: No JSON object could be decoded
```

Merci,
Éric

**Comment by ehoffman2** [comment]
Le problème est que la requête Web avec le client 'phone-android' ne fonctionne pas pour certains médias, comme les films/documentaires.

https://ici.tou.tv/presentation/alter-ego/S01E01?excludeLineups=True&smallWidth=188&mediumWidth=660&largeWidth=660&v=2&d=phone-android
retourne une erreur.

Mais avec le client 'android', ça fonctionne.  Ex:

https://ici.tou.tv/presentation/alter-ego/S01E01?excludeLineups=True&smallWidth=188&mediumWidth=660&largeWidth=660&v=2&d=android

Dans le fichier resources/lib/scraper.py, j'ai remplacé , à la ligne 23:

`emission = GET_HTML('http://ici.tou.tv/presentation' + PID + '?excludeLineups=True&smallWidth=188&mediumWidth=660&largeWidth=660&v=2&d=phone-android')`

par

`emission = GET_HTML('http://ici.tou.tv/presentation' + PID + '?excludeLineups=True&smallWidth=188&mediumWidth=660&largeWidth=660&v=2&d=android')`

Le résultat JSON donne moins d'infos (le champ 'Detail2' est manquant), mais ça fonctionne pour les documentaires.

J'ai eu moins de succès pour les films, problème de décodage, mais la requête fonctionne.

**Comment by anisite** [comment]
En fait il devrait y avoir un message d'erreur qui dit qu'il n'y a pas de DRM supporté sur la plateforme. Certains films sont mal catégorisé par tou.tv. mais j'avais fait un changement pour les lire mais je n'aime pas ça parce que d'autres ne fonctionnent pas alors j'ai voulu revenir au message informatif en les blocant tous et j'ai oublié un morceau.

**Comment by anisite** [comment]
Il y a un projet de tenter de supporter les DRM dans un avenir rapproché alors il faut garder espoir que ça marche un jour...

**Comment by anisite** [comment]
@ehoffman2 bonjour, une nouvelle version ici https://github.com/anisite/plugin.infologique.tou.tv/tree/DRM permet de supporter les DRM, si vous voulez tester avant la version finale!

**Comment by anisite** [comment]
La version finale 3.0.1 est sortie aujourd'hui, SVP ré-ouvrir un bug ou ré-ouvrir celui-ci si vous rencontrez des difficultés.
