### ISSUE TITLE
Pas un "issue". :) Un logo ? 

### ISSUE THREAD

**Issue by esenterre** [anisite/DepotQuebec#15]
Je me suis amusé à faire un logo. Peut-être que ça pourrait vous intéresser. 
![icon](https://user-images.githubusercontent.com/1243447/39944716-ac1269c2-5535-11e8-96e2-a6670498abff.png)

**Comment by dualB** [comment]
Héhé j'y avais pensé aussi, mais ça crée plus de confusion que de clarté :)

**Comment by johnboisvert** [comment]
Wow ca coche !

**Comment by mathieugouin** [comment]
Moi aussi j'aime bien!

**Comment by anisite** [comment]
Désolé mais mettre un logo du gouvernement sur un logo c'est pas une bonne idée côté droits et surtout que je travaille la... Ce serait pas mal conflictuel potentiellement comme situation.
