### ISSUE TITLE
Problème d'installation avec ICI tou.tv

### ISSUE THREAD

**Issue by pisabell** [anisite/DepotQuebec#16]
Bonjour,

J'ai essayé d'installer ici tou.tv 3.0.0-beta3 dur ma plateforme libreelec 8.0.2 / kodi 17.3. J'ai téléchargé le fichier ZIP sur un disque réseau, puis j'ai installé ce ZIP dans mon kodi.

L'installation a semblé se dérouler normalement, mais lorsque j'essaie de démarrer un vidéo. rien ne se produit.

En examinant mon kodi.log je vois des erreurs dès le démarrage de ici tou.tv. Le log commence comme suit:

09:35:33.104 T:140233114883840  NOTICE: [COLOR lightskyblue]VipSecrettv Wizard[/COLOR]: [Wiped] /storage/.kodi/temp/commoncache.db
09:35:33.104 T:140233114883840  NOTICE: [COLOR lightskyblue]VipSecrettv Wizard[/COLOR]: Ignore Log File: kodi.old.log
09:35:33.104 T:140233114883840  NOTICE: [COLOR lightskyblue]VipSecrettv Wizard[/COLOR]: Ignore Log File: kodi.log
09:35:33.104 T:140233114883840  NOTICE: [COLOR lightskyblue]VipSecrettv Wizard[/COLOR]: [Wiped] /storage/.kodi/temp/commoncache.socket
09:35:33.104 T:140233114883840  NOTICE: [COLOR lightskyblue]VipSecrettv Wizard[/COLOR]: [Success] cleared 4 files from /storage/.kodi/temp/temp
09:35:33.105 T:140233114883840  NOTICE: [COLOR lightskyblue]VipSecrettv Wizard[/COLOR]: [Auto Clean Up] Old Thumbs: On
09:35:33.109 T:140233114883840  NOTICE: [COLOR lightskyblue]VipSecrettv Wizard[/COLOR]: 146 total thumbs cleaned up.
09:35:33.357 T:140233114883840  NOTICE: [COLOR lightskyblue]VipSecrettv Wizard[/COLOR]: [Auto Clean Up] Packages: On
09:35:34.904 T:140233861478144   ERROR: GetDirectory - Error getting
09:35:45.746 T:140233114883840   ERROR: Previous line repeats 6 times.
09:35:45.746 T:140233114883840   ERROR: Traceback (most recent call last):
09:35:45.746 T:140233114883840   ERROR:   File "/storage/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutv.py", line 142, in goSync
09:35:45.748 T:140233114883840   ERROR:     response = scraper.POST_HTML("http://tv.infologique.net/TouTv/watched/", post_data)
09:35:45.748 T:140233114883840   ERROR:   File "/storage/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutvapiservice.py", line 56, in POST_HTML
09:35:45.749 T:140233114883840   ERROR:     response = opener.open(request)
09:35:45.749 T:140233114883840   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 429, in open
09:35:45.749 T:140233114883840   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
09:35:45.749 T:140233114883840   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
09:35:45.749 T:140233114883840   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
09:35:45.749 T:140233114883840   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
09:35:45.749 T:140233114883840   ERROR: URLError: <urlopen error timed out>
09:36:09.100 T:140233114883840   ERROR: NEWADDON Invalid Date Format "18 juin 2018"
09:36:09.101 T:140233114883840   ERROR: NEWADDON Invalid Date Format "11 juin 2018"
09:36:09.101 T:140233114883840   ERROR: NEWADDON Invalid Date Format "4 juin 2018"

Au besoin, je pourrais vous procurer un log plus complet.

Avez-vous une idée de quel est le problème?

Merci beaucoup,

Pierre
pierreisabelle009@gmail.com

**Comment by anisite** [comment]
Bonsoir, durant cette période j'avais une panne de serveur, est-ce que vous avez réessayer ces 2 dernières semaines?

**Comment by pisabell** [comment]
?Bonjour,


Merci de ce retour.


Hier, j'ai réinstallé le addon après avoir manuellement effacé tous les fichiers des versions précédentes et maintenant tout marche bien. Je ne sais pas si le problème était dans ces fichiers non effacés ou dans votre panne de serveur.


L'important est que ça marche maintenant.


Merci encore,


  Pierre

________________________________
De : anisite <notifications@github.com>
Envoyé : 11 juillet 2018 20:40
À : dualB/DepotQuebec
Cc : Isabelle, Pierre; Author
Objet : Re: [dualB/DepotQuebec] Problème d'installation avec ICI tou.tv (#16)


Bonsoir, durant cette période j'avais une panne de serveur, est-ce que vous avez réessayer ces 2 dernières semaines?

-

**Comment by anisite** [comment]
Merci du suivi.
