### ISSUE TITLE
Erreur au moment de cliquer sur un repertoire (Noovo)

### ISSUE THREAD

**Issue by richardsavage** [anisite/DepotQuebec#17]
Quand je clique sur un repertoire (ex. Beach Club), j'obtiens un erreur.

Apres avoir regarder le code et les logs, l'erreur arrive à ce moment:

        _duration = -1
        durationDiv = carte.find('ul', {"class": 'card__meta'})
        if durationDiv:
            duration = durationDiv.find('li').getText()
            try:
                duration = time.strptime(duration,'%M m %S s')
            except:
                try:
                    duration = time.strptime(duration,'%H H %M m')
                except:
                    duration = -1
            duration = **datetime.timedelta(hours=duration.tm_hour,minutes=duration.tm_min,seconds=duration.tm_sec).total_seconds()_**

Dans les logs j'obtiens un erreur comme quoi tm_hour n'est pas défini.

Nvidia Shield 2017 (Android 8.0 Oreo) firmware ver. 7.0.2
Kodi v17.6 "Krypton" (package DepotQc)
plugin Noovo, derniere version

Si nécéssaire, je vous transfererai les logs.

**Comment by anisite** [comment]
Je vais regarder ils ont du changer le site...

**Comment by anisite** [comment]
Ça été corrigé dans la version 0.5.5 Merci de votre signalement du problème, une chance que les gens comme vous prennent le temps, désolé du délai! Le déploiement devrais se faire chez vous d'ici 24 heures.
