### ISSUE TITLE
Nouvel addon pour Canal Vie

### ISSUE THREAD

**Issue by service-paradis** [anisite/DepotQuebec#19]
Salut,

Ce n'est pas vraiment un « issue ». J'ai créé récemment un addon (encore très minimal) pour écouter les vidéos qui se retrouvent dans la section WebTélé de Canal Vie.

Je me demandais si ça pouvait être intéressant pour le repo.

Je laisse le lien ici en attendant: https://github.com/service-paradis/plugin.canalvie.videos

**Comment by service-paradis** [comment]
Trop partiel et semble ne contenir pratiquement seulement des extras et pas d'épisodes....

**Comment by anisite** [comment]
J'avais fait ça pour pas mal tous les canaux de Bell Media (anciennement astral) mais malheureusement... pas de contenu, tout est rendu sur tou.tv de toute façon : https://ici.tou.tv/categorie/canal-vie
