### ISSUE TITLE
plugin.video.illicoweb-2.3.3.zip - Erreur Media encrypted avec les nouvelles émissions de TVA de septembre 2018

### ISSUE THREAD

**Issue by microcontroleur** [anisite/DepotQuebec#21]
En tentant de jour les nouvelles émissions de TVA, lorsque je démarre une émission (exemple: O' ou Le Jeu), j'obtiens un erreur 'Media Encrypted - cannot play'.

Testé sur LibreElec 8.9.04 (Kodi 18) et Windows 10 (Kodi 17).

Étrangement, rien dans les logs.

**Comment by marseneault** [comment]
IllicoWeb a toujours diffusé du contenu encrypté pour certaines de ses chaînes et jusqu'à maintenant nous n'avons pas de façon pour jouer ce contenu dans Kodi.  

Dernièrement, j'ai constaté, comme toi, que les émissions TVA sont maintenant aussi encryptés.

La technologie de inputstream.adaptive proposée par Kodi ne fonctionne pas présentement avec l'encryption de IllicoWeb.

Graduellement, tout ce qui restera accessible sera les chaînes en direct.

**Comment by microcontroleur** [comment]
Merci de la réponse.  On va utiliser leur site web alors.

**Comment by anisite** [comment]
@marseneault quel est le type de protection de illicoWeb ?

**Comment by marseneault** [comment]
Microsoft PlayReady si je me souviens bien.   Il y a longtemps que ce serait fait si c'était Widevine...

**Comment by Moluv** [comment]
plugin.video.illicoweb-2.3.3.zip - Erreur Media encrypted.Tous les channels Ne Fonctionne plus. Kodi 17.6 Quelqu un d autre a un probleme? 
mots de passe et nom ok, site illicoweb ok, juste sur kodi que ca ne fontionne plus.

**Comment by marseneault** [comment]
De nombreuses chaînes en direct sont maintenant encryptés par PlayReady
DRM, comme c'était déjà le cas avec beaucoup du contenu sur demande.  Il ne
semble pas y avoir de solutions pour faire marcher ce DRM avec Kodi alors je suis en attente de changements futurs dans Kodi ou dans Illicoweb pour réparer l'addiciel.

**Comment by boucchar** [comment]
Salut Matthieu, je ne sais pas si cela peut aider, mais j'ai trouver cet article concernant les DRM dans KODI 18... https://www.redmondpie.com/kodi-officially-adds-drm-with-v18-alpha-2-release/
Merci pour le support!
