### ISSUE TITLE
Erreur de lecture de Occupation Double Grèce et OD + en direct

### ISSUE THREAD

**Issue by TT-Hipster1941** [anisite/DepotQuebec#23]
sur la version 0.5.5 Les deux liens pour Occupation Double Grèce et OD + en direct en fonctionnent pas faute de redirection vers 

https://occupationdouble.noovo.ca/grece

et non pas :

https://noovo.ca/emissions/occupationdouble

S'il vous plait agir vite, j'ai une fille qui s'peu pu maison.

Merci!

**Comment by anisite** [comment]
v1.5.6 released
