### ISSUE TITLE
teleqc marche pas 

### ISSUE THREAD

**Issue by lefou66** [anisite/DepotQuebec#25]
teleqc marche pas??
kodi17.6
Android
tx95

**Comment by dualB** [comment]
Bonjour, pourriez-vous préciser quelle version de l'additiel?
Est-ce pour tous les contenus ou des contenus spécifiques?

**Comment by lefou66** [comment]
3.2.0 et tout le contenu

**Comment by dualB** [comment]
Ok merci, est-ce que de vider le cache permet de régler le problème (dans les paramètres de l'additiel) ?

**Comment by dualB** [comment]
C'est bon, j'ai isolé le bug, ce sera corrigé.

**Comment by lefou66** [comment]
Parfait merci...en mise à jour auto?

**Comment by dualB** [comment]
Oui ce sera en mise à jour automatique.

**Comment by dualB** [comment]
Anisite, as-tu déjà vu ce type de problème-là, j'explique:
Les requêtes à l'URL "https://mnmedias.api.telequebec.tv" , avec urllib2.urlopen() me donne maintenant une erreur de type "certificate_verify_failed". Ce que j'ai trouvé comme solution facile, c'est de désactiver la vérification SSL (avec un paramètre "context = ssl._create_unverified_context()") mais cela semble trop boiteux comme façon de faire.... des suggestions?

**Comment by anisite** [comment]
ont-ils un certificat non supporté par kodi signé trop fort? ils l'ont
changé le 11 octobre

Le ven. 26 oct. 2018 à 07:44, Claude Bouchard <notifications@github.com> a
écrit :

**Comment by lefou66** [comment]
merci pour le support! Ça fonctionne..
