### ISSUE TITLE
plugin tou.tv - Certains vidéos Extra jouent en vidéodescription avec les versions 3.0.1 et 3.0.2

### ISSUE THREAD

**Issue by osmose99** [anisite/DepotQuebec#26]
La nouvelle série Plan B et Trop jouent en videodescription (Peut-être d'autres aussi). Ces deux séries sont accessible avec un compte EXTRA.  
J'ai testé avec le plugin Widevine et HLS (DRM activé).  Même résultats.
Tout fonctionne sans problèmes avec la version 3.0.0 beta 2 du plugin.

OS: LibreELEC (official): 8.90.006
Version du plugin: 3.0.1 et 3.0.2
Plate-forme: RaspberryPi 2 et PC

**Comment by osmose99** [comment]
La nouvelle série Plan B et Trop jouent en videodescription (Peut-être d'autres aussi). Ces deux séries sont accessible avec un compte EXTRA.  
J'ai testé avec le plugin Widevine et HLS (DRM activé).  Même résultats.
Tout fonctionne sans problèmes avec la version 3.0.0 beta 2 du plugin.

OS: LibreELEC (official): 8.90.006
Version du plugin: 3.0.1 et 3.0.2
Plate-forme: RaspberryPi 2 et PC

**Comment by odubuc** [comment]
J'ai le même problème avec la série Lâcher Prise. 

Kodi: v18.0
plugin: v3.0.2
Win10 (1809)

**Comment by anisite** [comment]
je crois que le problème est résolut sur la version 4.0.1

**Comment by service-paradis** [comment]
De mon côté, plusieurs émissions sont également en vidéodescription. J'ai la version 4.0.3.

**Comment by anisite** [comment]
Il est possible de flipper l'audio dansa liste des pistes. Par contre il faut recommencer a chaque fois. Je n'ai pas d'autres solutions pour le moment
