### ISSUE TITLE
plugin.video.illicoweb-2.3.3.zip - Erreur Media encrypted.Tous les channels

### ISSUE THREAD

**Issue by Moluv** [anisite/DepotQuebec#27]
Salut :)
plugin.video.illicoweb-2.3.3.zip - Erreur Media encrypted.Tous les channels Ne Fonctionne plus. Kodi 17.6 Quelqu un d autre a un probleme? 
mots de passe et nom ok, site illicoweb ok, juste sur kodi que ca ne fontionne plus.

**Comment by marseneault** [comment]
De nombreuses chaînes en direct sont maintenant encryptés par PlayReady DRM, comme c'était déjà le cas avec beaucoup du contenu sur demande. Il ne semble pas y avoir de solutions pour faire marcher ce DRM avec Kodi alors je suis en attente de changements futurs dans Kodi ou dans Illicoweb pour réparer l'addiciel.

**Comment by Moluv** [comment]
ah bon ok, donc plus de hockey pour moi,
Merci :)
