### ISSUE TITLE
Illicoweb TV 2.3.3 ne démarre pas

### ISSUE THREAD

**Issue by dover19** [anisite/DepotQuebec#28]
Je viens de m'abonner à Illicoweb et j'ai installé le addon dans kodi pour la première fois et il ne veut pas démarrer.

Voici mon log:
https://paste.kodi.tv/iguquxizaw

Merci

**Comment by marseneault** [comment]
Ça vient d'un problème de OpenSSL dans LibreElec. Pour être franc, je suis très surpris que ça soit encore un problème puisque je l'ai vu pour la première fois il y a quelques années. Je n'ai pas trouvé de solutions à cette époque. Est-ce que ton LibreElec est à jour?

Je vais garder le issue ouvert quelques temps afin de permettre à d'autres de t'aider sur ta plate-forme.

**Comment by dover19** [comment]
Disons que j'ai la version stable de LibreElec la plus récente.

**Comment by maquintal** [comment]
Bonjour, j'ai libreelec version 9.0.0 et mon illicotv ne fonctionne plus, depuis quelque temps
ca indique un message Media encrypted - cannot play.

**Comment by anisite** [comment]
Aucune activité
