### ISSUE TITLE
Le serveur vous parle : Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by TT-Hipster1941** [anisite/DepotQuebec#30]
Bonjour, depuis vendredi dernier Radio-canada aka Tout.tv semble avoir changer quelque chose dans leur tags d'emissions toutes les émissions sans exceptions sont reconnue comme des emissions EXTRA alors quelle ne le sont pas. Ceci a été constaté sur deux setup différents. Et ce malgré qu'un compte est configuré et que l'options anti-DRM est activé. Tout les autres modules de Dépôt Québec fonctionnent bien.

Version de l'app : ICI Tout.tv 3.0.2

Problème reproduit sur : 
Raspberry Pi 3
Libreelec 8.95
Kodi 18.0

MacOs 10.14.1
Kodi 18.0

Les deux messages obtenu sont celui dans le titre  et celui-ci:
Oups
Le contenu n'est pas disponible pour les non abonnés extra

Merci pour tout vous êtes awesome!!

**Comment by captzapo** [comment]
Merci Fultos pour la description détaillée de la problématique.

J'aimerais juste ajouter que je reçois les mêmes messages d'erreurs sur LibreElec 9 (Kodi 18) que ce soit en mode HLS ou widevine.

Merci pour tout le travail accompli jusqu'ici et bonne continuation à la communauté.

**Comment by captzapo** [comment]
Le plugin fonctionne de nouveau ce soir avec District 31 sur LibrElec 9 (Kodi 18).

**Comment by TT-Hipster1941** [comment]
Je confirme, ça recommencer à fonctionner maintenant, je l'ai ré-éssayé hier pour sortir plus d'info dans les logs et ça ne fonctionnait clairement pas. On peu donc conclure que c'est du côté de Radio-Canada qu'ils ont fait des changements de tagging par devices ou kkchose demême et que ça planter temporairement.

Je ferme le billet.
