### ISSUE TITLE
Télé-Québec séries vide

### ISSUE THREAD

**Issue by franckgaga** [anisite/DepotQuebec#32]
Certaines séries sortent vides dans l'addiciel de télé-québec. Ces mêmes séries peuvent être visionner sur le site web de Télé-Québec. Exemple : "De garde 24/7" (dans documentaires), il y a actuellement 4 saisons que l'ont peut visionner. J'ai tenter de vider la cache de l'addiciel sans succès...

Merci !

**Comment by dualB** [comment]
Il y a déjà un issue là-dessus.

**Comment by franckgaga** [comment]
Oups en effet j'ai oublié d'aller voir dans le dépôt de télé-québec. Merci pour votre excellent travail !!!
