### ISSUE TITLE
noovo fonctione plus

### ISSUE THREAD

**Issue by maxmasou** [anisite/DepotQuebec#34]
Depuis cette semaine seul occupation double marche. J'ai essayé de régler le problème, mais il semblerait que se sois au delà de mes compétences! voici l’erreur dans le log:
```
2019-02-21 17:15:38.740 T:140292883740416   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "/home/masou/.kodi/addons/plugin.video.vtele/default.py", line 115, in <module>
                                                navig.jouer_video(SOURCE_URL)
                                              File "/home/masou/.kodi/addons/plugin.video.vtele/resources/lib/navig.py", line 170, in jouer_video
                                                log(video['data-video-id'])
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
2019-02-21 17:15:38.812 T:140294130316096   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vtele/?url=https%3A%2F%2Fnoovo.ca%2Fvideos%2Fl-amour-est-dans-le-pre%2Fepisode-1&sourceUrl=https%3A%2F%2Fnoovo.ca%2Fvideos%2Fl-amour-est-dans-le-pre%2Fepisode-3-premiere-journee-a-la-ferme-1] 
```

**Comment by johnboisvert** [comment]
Meme chose ici ma blonde tripe a la plus souper presque parfais ont mange du kraft diner depuis 4 jours !! HELP lol merci en passant pour votre bon travail

**Comment by maxmasou** [comment]
Simonac j'ai trouvé! Finalement c'était assez basic! Dans le fichier navig.py de l'addon, il suffit de remplacé:

```
video = soup.find("video")    
log("video")
log(video)
```
par: 

```
video = soup.find("video-js")
log("video-js")
```

Le log de Kodi était pourtant très claire. En grand cabochon que je suis j'ai cherché ailleurs pendant 1 semaines. Hi lala!

**Comment by johnboisvert** [comment]
Très fort ! t'es loin d'être un cabochon moi je comprend absolument rien !! lol 
savez vous si ca va etre updater cette sem?

**Comment by maxmasou** [comment]
J'essaie de faire une "pull request" présentement, sa devrait pas être trop trop long!

**Comment by johnboisvert** [comment]
Ohh merci :)

**Comment by johnboisvert** [comment]
Il ne fonctionne pas plus une mise a jour va ce faire ? merci :)

**Comment by maxmasou** [comment]
Tu peux aller sur https://github.com/maxmasou/plugin.video.vtele et télécharger ma mise à jour en cliquant sur "clone or download". Après ça tu peut installer le ZIP dans kodi. J'ai fait une "pull request" sur le git du projet (https://github.com/anisite/plugin.video.vtele), mais malheureusement j'ai eu aucune réponse et ça fait maintenant 7 jours.

**Comment by johnboisvert** [comment]
ok moi je vais pouvoir mes 2 freres sont pas trop a l'aise
ils attendrons la mise a jour merci

**Comment by dualB** [comment]
Nos développeurs sont bénévoles et trouvent le temps pour compléter les modifications lorsque cela est possible. Chaque modification doit être testée avec un minimum de soin avant de rejoindre le dépôt principal. Merci de votre patience.

**Comment by johnboisvert** [comment]
Aucun probleme vous faite un tres bon travail je ne chialerai jamais :)

**Comment by RicPigeon** [comment]
En attendant, j'ai pris la version de maxmasou et ça fonctionne bien.

**Comment by sptessier** [comment]
J'ai installer la version de @maxmasou hier soir et ca fonctionne! Merci d'avoir pris le temps pour le débogage.

**Comment by maxmasou** [comment]
Nouvelle version, donc problème réglé!
