### ISSUE TITLE
Tou.tv - Mode extra connecté, contenu non disponible 

### ISSUE THREAD

**Issue by ekinoxben** [anisite/DepotQuebec#36]
Bonjour, 
Je viens de faire l'update à la version 4.0.0 pour me connecter à tou.tv. Par contre, même en étant membre et connecté Extra, je ne peux pas voir le contenu proposé... 
Deux erreurs s'affichent une à la suite de l'autre.
"Le contenu sélectionné est disponible seulement en Premium"
"Le contenu n'est pas disponible pour les non abonné Extra"
J'ai tenté les 3 types de flux HLS, RTSP et widevine, avec et sans l'option DRM coché... rien ne passe.

Je suis avec Kodi 17.6, tvbox android leelbox m9s.
Est-ce que je devrais updater aussi ma version de Kodi pour la 18?

**Comment by anisite** [comment]
Difficile a dire, il est trop tôt, avant ça fonctionnait bien? Je sais que les contenus sont de plus en plus protégés et que pas mal juste widevine fonctionne maintenant... C'est certain que Kodi 18 est le premier a supporter officiellement les flux avec drm. De passer à 18 devrait aider, cela va t-il régler votre problème... Bonne question.

**Comment by ekinoxben** [comment]
En fait, je crois que le contenu extra pour ma part a arrêté de fonctionner à la version 3.0.2. (toujours avec kodi 17.6) Mais je me servait de ma androidbox pour écouter certaines émissions qui n'étaient pas forcément extra... Mais sinon avant ça, (version 3.0.0 de l'appli tou.tv) le contenu extra fonctionnait bien oui.
Je tenterai de faire l'update a kodi 18 en fds, je verrai si ça règle le problème.

**Comment by anisite** [comment]
@ekinoxben j'ai livré une version 4.0.1 qui retire toute utilité des choix rtsp, hls, widevine et drm du menu et qui force un seul mode. est-ce fonctionnel maintenant ?

**Comment by ekinoxben** [comment]
> @ekinoxben j'ai livré une version 4.0.1 qui retire toute utilité des choix rtsp, hls, widevine et drm du menu et qui force un seul mode. est-ce fonctionnel maintenant ?

Bonjour,
Je viens d'installer la 4.0.1. J'ai aussi entre temps installé Kodi 18.2 sur ma android box. Je n'ai plus d'erreur (le serveur vous parle) lorsque je clique sur une émission extra, mais le contenu ne démarre toujours pas. J'aimerais bien te fournir un log de ce qui se passe, mais je ne sais pas trop comment/où avec la tvbox android... 
Je vois aussi toujours les 3 types de flux à sélectionner dans les propriétés de l'app, est-ce normal?

**Comment by anisite** [comment]
@ekinoxben quelqu'un sur amazon dit que cette box là n'a pas de licence DRM widevine intégrée... ça expliquerait pourquoi ça ne fonctionne pas... je vais voir pour te trouver une solution... la vraie application tou.tv fonctionne t-elle sur cette box?

**Comment by anisite** [comment]
J'ai trouvé la liste exacte des version supportant widevine chez kodi :

> WIDEVINE_MINIMUM_KODI_VERSION = {
    'Android': '18.0',
    'Windows': '17.4',
    'Linux': '17.4',
    'Darwin': '17.4'
}

**Comment by ekinoxben** [comment]
> @ekinoxben quelqu'un sur amazon dit que cette box là n'a pas de licence DRM widevine intégrée... ça expliquerait pourquoi ça ne fonctionne pas... je vais voir pour te trouver une solution... la vraie application tou.tv fonctionne t-elle sur cette box?

J'ai aussi essayé ça récemment. La version sur Google Play ne veux pas télécharger alors j'ai cherché ailleurs. La version 4.0.0.8 trouvé ici : https://apkpure.com/ici-tou-tv/tv.tou.android ne fonctionne pas plus (ouvre et referme tout de suite)
Par contre, je viens de me rendre compte qu'il y a une version plus récente que je pourrais installer ici: 
https://ici-tou-tv.fr.aptoide.com/
Je vais la tester plus tard.

**Comment by anisite** [comment]
je pense qu'il y a un ptit log viewer sur kodi que tu peux installer:

> The home screen
Add-ons
Download
Program Add-ons
Log Viewer for Kodi
Install

sinon, est-ce que le plugin t'a demander d'installer les DRM widevine et les as installés ?

**Comment by anisite** [comment]
Pour le moment je ne peux pas comprendre d'ou vient le problème. habituellement android c'est la plateforme la plus facile pour le DRM widevine, puisque c'est google les 2. reviens moi si tu as plus d'infos sur ton log svp

**Comment by erikatremblay** [comment]
Pour ma part, la nouvelle version 4.0.2 ne fonctionne pas du tout avec kodi 17.6

Même si je met un compte EXTRA et même un compte normal sa fait la même chose, l’émission Ouvre mais l’image fait plein de petits carrés de couleur et pas de Son! 😓

Pourtant avant la nouvelle mise à jour tout fonctionnait bien mise à part les émissions en extra!

**Comment by erikatremblay** [comment]
J’aimerais Également ajouter que comme ekinoxben moi aussi je vois encore les 3 types de flux avec l’option de désactiver les DRM est-ce normal?

**Comment by anisite** [comment]
Oui les options sont encore là je n'ai pas eu le temps de faire le ménage. Malheureusement Kodi 17 n'est plus jeune et il ne décode pas les drm. Tou.tv ont resserrer la sécurité de leur contenu les nouveaux épisodes ne fonctionnent plus en plus. Alors j'ai tout retiré. Reste que le widevine et il faut les drm. Selon ta plateforme (os) voici le minimum qu'il te faut 

WIDEVINE_MINIMUM_KODI_VERSION = {
'Android': '18.0',
'Windows': '17.4',
'Linux': '17.4',
'Darwin': '17.4'
}

Si c'est bien ce que tu as ... Il est parfois utile de désinstaller Kodi. En tout cas sur Windows la réinstallation après suppression ma déjà sauver la vie. Sur tu as Kodi sur le Windows store, ce n'est pas supporté.

**Comment by anisite** [comment]
À voir : https://github.com/dualB/DepotQuebec/issues/49
