### ISSUE TITLE
WOW!

### ISSUE THREAD

**Issue by alKODIque** [anisite/DepotQuebec#37]
Juste  un petit mot pour vous féliciter des dernières mises à jour que vous avez effectué dernièrement. Étant une abonnée de l’EXTRA,  les ajouts et modifications de l’additiel me forcent à demeurer plus longuement devant mon écran hihi!  

Un grand BRAVO et un énorme MERCI pour tout ce travail que vous nous partagez!

Au plaisir!

**Comment by anisite** [comment]
Bonjour, merci, content de voir que c'est utile à quelque uns! difficile de savoir combien l'utilisent, c'est toujours plaisant de se faire remercier 👍 au plaisir @alKODIque

**Comment by sylgrenier** [comment]
Merci a vous pour les corrections dans Tou.TV, c est vraiment tres hot ce que vous avez fait.  C est le Add-on Kodi que je vais le plus souvent.  J ai une suggestion pour vous, je suis pas un dev.  Mais j ai trouvé qu on peux regarder RDI et Radio Canada avec des streams, Donc la fonction pourrait etre ajouté dans votre add-on.  J ai fabriqué un lien STRM. que je met dans un fichier avec l extension STRM. Je met juste ceci a linterieur https://rcavlive.akamaized.net/hls/live/704025/xcanrdi/master_2500.m3u8, et ainsi je regade RDI en direct. Ca marche super bien.

Merci encore pour votre travail.

**Comment by alKODIque** [comment]
Ce que j’apprécie le plus, c’est que maintenant, il est possible d’ajouter des éléments de TOU.TV en « Widget » dans kodi. Ce qui n’était pas le cas avant.  (Voir photo attachée, skin utilisé: Estuary MOD v.2)

![814A71C8-366B-4ED7-8421-91D7AA035F4A](https://user-images.githubusercontent.com/49578130/57553034-b1841980-733b-11e9-9422-2df7572c75e8.jpeg)

**Comment by alKODIque** [comment]
> Bonjour, merci, content de voir que c'est utile à quelque uns! difficile de savoir combien l'utilisent, c'est toujours plaisant de se faire remercier 👍 au plaisir @alKODIque

Je crois que tout Québécois qui utilise kodi utilise également Tou.tv... En seulement, la majorité est silencieuse et c’est dommage qu’il y ait aussi peu de feed-back pour vous. @anisite

**Comment by zoneamick** [comment]
Effectivement très intéressant! Tellement que je me suis mis a lire sur Python et je commence a construire un plugin de mon côté sur un canal local comme test si cela fonctionne on pourras peut-être le "forker" à dépôt Quebec.

**Comment by anisite** [comment]
@sylgrenier c'est dans les plans d'offrir la TV en direct, comme sur le site web. pas plus, pas moins. Mais le temps me manque.

@zoneamick le python c'est super.

**Comment by patrice-geo** [comment]
Je seconde. Merci pour ce repo etplugins, ça rend la vie plus facile à bien des gens!
