### ISSUE TITLE
Ajout de plugin a DepotQuebec

### ISSUE THREAD

**Issue by zoneamick** [anisite/DepotQuebec#38]
Bonjour, je suis en construction d'un plugin d'une station de télévision de Québec il est fonctionnel à 75% je pourrais vous le partager je ne sais pas avec qui et de quel manière il est préférable de communiquer.

[https://github.com/zoneamick/repokodi](url)

**Comment by dualB** [comment]
Bonjour, l'ajout de nouveaux addiciels dépend de plusieurs facteurs, notamment s'il cadre avec la mission du dépôt, sa fonctionnalité, sa robustesse, etc. En tant que développeurs nous-mêmes, nous vous encourageons à poursuivre sa création, mais nous ne pouvons pas nous prononcer à ce stade-ci.

**Comment by zoneamick** [comment]
Excellent merci!
