### ISSUE TITLE
Tout.tv ne fonctionne pas

### ISSUE THREAD

**Issue by lefou66** [anisite/DepotQuebec#39]
J'ai une boîte Android avec Kodi 18.2 et tout.tv ne marche pas.Jai essayé avec l'apk mais les vidéos ne partent pas,j'ai aussi essayé d'enlever les drm.Peut être que ma version Android est trop vieille,je crois que c'est 7.1.1.Par contre marche très bien sur ma shield.

**Comment by anisite** [comment]
Si les vidéo ne fonctionnent pas avec l'application toutv, difficile de faire fonctionner avec kodi...
