### ISSUE TITLE
Plugin tou.tv -- Le contenu Extra ne fonctionne pas

### ISSUE THREAD

**Issue by slaadvak** [anisite/DepotQuebec#4]
Lorsque je demarre une émission "extra" avec le addon tou.tv j'obtiens le message d'erreur suivant: Aucun DRM n'est supporté pour cette plateforme. J'utilise LibreELEC avec Kodi 17.

Il semblerait que la recherche du CLAIMS dans scrapper.py::getVideoExtra ne fonctionne plus. Le deviceType est setté à "iphone4", mais cette plateforme n'est plus reconnu par le service de tou.tv. Après plusieurs essais et recherches, j'ai vu que trois deviceType fonctionnent : "html5cenc", "androidcenc" et "ioscenc". Pour que le format du programme soit accessible en m3u8, c'est ce dernier deviceType qu'il faut choisir.

Donc, dans scrapper.py::getVideoExtra il faut changer la ligne
```
content = GET_HTML_AUTH('https://services.radio-canada.ca/media/validation/v2/?appCode=toutv&deviceType=iphone4&connectionType=wifi&idMedia=' + IdMedia + '&claims=' + claims + '&output=json')
```
en
```
content = GET_HTML_AUTH('https://services.radio-canada.ca/media/validation/v2/?appCode=toutv&deviceType=ioscenc&connectionType=wifi&idMedia=' + IdMedia + '&claims=' + claims + '&output=json')
```

**Comment by anisite** [comment]
Juste changer l'URL n'est pas suffisant, il faut aussi récupérer la clef DRM et c'est loin d'être simple, pour prévenir les gens il est préférable d'afficher le message de la plate-forme introuvable sinon il n'y aura qu'une image noire...

**Comment by slaadvak** [comment]
Ça c'est intéressant.

Tous les contenus que j'ai essayés fonctionnent bien chez moi, sauf pour un que j'ai testé après avoir ouvert ce ticket, et c'est Downtown Abbey. La dizaine d'autres fonctionne parfaitement. Pour DA, j'ai effectivement une image noire et je vois bien que ffmpeg n'est pas capable de faire le décodage.

Est-ce que vous avez d'autres exemples d'émission qui ne se décodent pas correctement? Si oui, avez-vous vous une façon de faire pour les identifier avant ou au moment la lecture?




lundi 9 janvier 2017 02:37 -0500 de anisite  <notifications@github.com>:

**Comment by anisite** [comment]
Bonjour, 
merci des recherches et du temps pour écrire ici, il y aurait probablement une façon d'identifier, mais de votre côté en avez-vous une émission qui est lisible en devicetype ioscenc et pas en iphone4?

J'ai même pris le temps cette nuit après l'ouverture du billet de faire un wireshark avec le chromecast pour voir comment lui il décode et c'est android_phone je pense le type, par contre, c'est toujours un contenu avec DRM, donc... pas plus avancé 👎

**Comment by slaadvak** [comment]
Bonjour,

De mémoire, les émissions suivantes ne fonctionnent pas avec iphone4 (ça 
affiche le message d'erreur du serveur) mais fonctionnent avec ioscenc:
- Les aventures du pharmachien
- Série Noire
- Les Simone
- Les Pays d'en haut
... et deux ou trois documentaires sur ICI Explora.

Peut-être que les émissions que Radio-Canada achètent de l'extérieur, 
comme Downtown Abbey, sont encodées différement ?

Vincent

**Comment by anisite** [comment]
iosenc a été mis en place dans la version 2.0.5, on va voir si je laisse ça là ou non.
