### ISSUE TITLE
Video description 

### ISSUE THREAD

**Issue by erikatremblay** [anisite/DepotQuebec#41]
Dans tou.tv tout fonctionne bien sur kodi 18.2 mais j’ai un mini problème les émissions sont toutes en vidéo description 🤦‍♀️ Ahah je sais pas trop pourquoi j’ai un compte extra j’ai essayé de jouer dans les settings mais rien à faire je ne réussi pas à enlever cela ! Quelqu’un peut m’aider ?

**Comment by davidbellemare** [comment]
Generalement, il y a 2 sources audio: la premiere avec la video description et la 2e sans video description. Tu peux le changer dans le player. C'est ce que tu as fais?
