### ISSUE TITLE
Tou.TV - Pas de son

### ISSUE THREAD

**Issue by levelKro** [anisite/DepotQuebec#44]
RCA Viking Pro 10" - Android 6.0
Kodi 18.3 (google play)
Installation de la version 4.1.1 du plugin (sans autre version avant, clean)
Je suis Extra, et identifié sous le plugin.
Je vois l'ensemble, j'arrive à lire les vidéos, mais aucun son.
J'ai tenté de changer le type de flux; HLS, RTSP et WIDEVINE aucun changement sur ce problème. Avec ou sans DRM.
Je vais tester avec mon Raspberry Pi 3 Model B sous OpenElec bientôt, si ya un bug, j'update ce post.

Et en passant, merci aux auteurs (et aidants) du plugin.

**Comment by levelKro** [comment]
OpenElec n'est plus compatible (n'a pas la dernière version de Kodi)
Sous Android, les codec et dépendances requises ne semble pas inquiété le plugin, sous LibreElec, j'ai des invitation pour les installer.

**Comment by anisite** [comment]
Voir cet issue https://github.com/dualB/DepotQuebec/issues/49
