### ISSUE TITLE
NOOVO : Manque épisodes OD:Afrique Du Sud, À table avec mon ex et autres

### ISSUE THREAD

**Issue by kevint277** [anisite/DepotQuebec#46]
Bonjour,

Il semble que l'addon ne répertorie pas bien les épisodes de certaines nouvelles émissions, comme Occupation Double Afrique du Sud et À table avec mon ex. Je crois que ça avait fait la même chose l'an dernier

**Comment by anisite** [comment]
Noovo fait des changements pour la rentrée chaque année, étant donné que je n'utilise que rarement l'application, merci de m'avoir prévenu. La version 0.6.0 est en cours de déploiement et devrait corriger le problème. Merci.

**Comment by drividor** [comment]
Ma femme aimerais voir occupation double Bali comme sur le site mais on ne trouve pas le dossier dans Noovo

**Comment by anisite** [comment]
Corrigé depuis un moment
