### ISSUE TITLE
Télé QC 

### ISSUE THREAD

**Issue by lefou66** [anisite/DepotQuebec#47]
Bonjour, depuis quelques temps télé QC l'ag beaucoup. Ça doit venir de leur site mais je me demandais si vous pouvez faire quelque chose pour améliorer ça.Je suis certain que le problème vient pas de chez nous.Jutilise une shield sur Kodi 18.4 avec internet 400 direct

**Comment by boucchar** [comment]
Même chose chez moi, je doute que ça vienne de leur site.

**Comment by dualB** [comment]
J'imagine que cet issue n'est plus pertinente.
