### ISSUE TITLE
Noovo Simpson

### ISSUE THREAD

**Issue by Ratz1978** [anisite/DepotQuebec#48]
Bonjour et merci pour votre travail je me demande avec Noovo kodi 17.6 je ne vois pas les emission de Simpson jai un error

16:47:30.867 T:7024   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vtele/?url=https%3A%2F%2Fnoovo.ca%2Farticles%2F10-costumes-pour-les-megafans-des-simpsons-photos&sourceUrl=https%3A%2F%2Fnoovo.ca%2Farticles%2Fun-episode-des-simpson-inspire-de-stranger-things-pour-lhalloween]

**Comment by anisite** [comment]
Bonjour les épisodes des Simpson ne sont pas disponibles sur Noovo.ca. ça explique votre incapacité à faire jouer les épisodes. https://noovo.ca/emissions/les-simpson
