### ISSUE TITLE
TVA

### ISSUE THREAD

**Issue by pc1984** [anisite/DepotQuebec#5]
Bonjour! 

D'abord, je voudrais vous féliciter pour votre excellente extension!

Je vous écris non pas pour souligner un problème, mais plutôt faire une suggestion/demande!

Est-ce que vous pourriez ajouter un plugin vers le site http://videos.tva.ca/ ou avec l'application TVA - Mobile ? (Je ne m'y connais pas beaucoup en programmation)

Merci!!!!

Phil

**Comment by dualB** [comment]
Bonjour!
Le développement des additiels se fait selon les intérêts propres à chaque développeur qui les créent et les entretiennent bénévolement.
Essaie de convaincre un ami passionné de programmation, qui a un peu de temps libre, et qui a besoin d'écouter les contenus vidéos de TVA, de le développer?

**Comment by mickybart** [comment]
Bonjour,

De mon cote je suis intéressé par travailler sur le support de http://videos.tva.ca/
En revanche je voulais partir du plugin toutv pour ne pas commencer de zero mais il semble que le code source ne soit pas disponible et le lien dans le README.md référence un repo github avec la version binaire 1.0.9

Je n'ai jamais écris d'extension pour kodi donc cela m'aiderai de ne pas partir de zéro. Merci d'avance si vous avez des infos.

EDIT: Pour info il semble qu'il existe une base : https://github.com/anisite/plugin.infologique.TVAgo

**Comment by dualB** [comment]
As-tu ouvert nos addiciels (le code source)? Ce serait une bonne source d'informations pour débuter.

**Comment by dualB** [comment]
Tu peux simplement le télécharger à partir de ce dépôt, en fichier zip (version la plus récente  : https://github.com/dualB/DepotQuebec/blob/master/plugin.infologique.tou.tv/plugin.infologique.tou.tv-2.0.4.zip

**Comment by juju2143** [comment]
C'est vrai que ça serait totalement génial, en fait c'est pas mal pour ça que j'ai installé Kodi sur la télé de ma mère. Avec un peu de recherches, j'ai déterminé qu'on pourrait juste récupérer un plugin qui fonctionne avec un API appelé Brightcove, l'adapter un peu à nos besoins et ça ferait l'affaire. Ça m'a l'air assez simple, je regarde ça et je vous en donne des nouvelles.

**Comment by juju2143** [comment]
Y'a ce type qui essaie, ça a l'air de marcher comme sur Noovo.

https://github.com/anisite/plugin.infologique.TVAgo

**Comment by dualB** [comment]
Ce "type" dont tu parles est notre développeur actuel de Noovo et Tou.TV :)

**Comment by madmaxtrois** [comment]
Un autre "type" a tenté quelque chose avec le code déjà commencé de Anisite. Bien que c'est une version préliminaire et qu'il reste du travail, il est maintenant possible de partir des vidéos de la section Rattrapage. Voici ce que j'ai fait très rapidement ce soir :

https://github.com/anisite/plugin.infologique.TVAgo/pull/2

J'ai fait un pull request pour montrer que quelqu'un est en train de faire quelque chose.

**Comment by dualB** [comment]
On supporte l'initiative, c'est toujours plaisant de voir d'autres personnes prendre part à l'évolution des nouveaux additiels! Continuez!

**Comment by juju2143** [comment]
Ahhh, j'aime ça, je teste ça ce soir :)

**Comment by anisite** [comment]
@madmaxtrois Ce qui est dommage, c'est que j'ai fini par en faire un peu ce soir, j'ai effectué pas mal les mêmes changements que toi. Je vais regarder pour fusionner ça, mais le code fait pas mal la même chose.

**Comment by juju2143** [comment]
Eh, dans tous les cas, ça marche super et on peut espérer que le code s'en trouvera amélioré et sera dans le dépôt dans les prochains jours :)

Et ma mère vous remercie :)

**Comment by mathieugouin** [comment]
Bonjour, je suis encore sur Kodi 16.1.  Est-ce compatible?
Merci pour votre excellent travail!

**Comment by anisite** [comment]
Normalement oui... as tu la v. 0.0.2 ?

**Comment by mathieugouin** [comment]
@anisite : Oui j'ai essayé la 0.0.2.  Ça marche partiellement on dirait.  Je vois les vidéos, je n'ai par contre aucun sons sur tous les vidéos que j'ai essayé.  Ça vous dit qqch?

J'ai essayé aussi la version TVA de service-paradis et même problème: https://github.com/service-paradis/plugin.tva.videos/issues/2

**Comment by anisite** [comment]
@mathieugouin j'ai vu que ça a fonctionné en MP4. mais pourquoi es-tu encore avec kodi 16?

**Comment by mathieugouin** [comment]
@anisite , Je suis sur un Raspberry Pi 3.  J'ai fait un test de migration sur Kodi 17 et mon système semblait beaucoup plus lent.  Peut-être quelqu'un pourrait me guider si c'est juste moi?  Aussi je me sentais vraiment perdu avec le nouveau skin...  

Si ça peut aider, je suis avec XBian sur Raspberry Pi 3.

Merci!
