### ISSUE TITLE
Illicoweb 2.3.3 a cesser de fonctionner

### ISSUE THREAD

**Issue by Rick9898** [anisite/DepotQuebec#52]
Illicoweb 2.3.3 a cesser de fonctionner la fin de semaine dernière (14 décembre 2019).

Ça arrêter de fonctionner en même temps sur mes 2 firestick. Je aussi tester sur un ordinateur et ça ne fonctionne pas non plus.

J'ai remarqué que la version de Python avait été mise à jour. Est-ce relier?

**Comment by ghost** [comment]
Bonjour,
Ilicoweb a cessé de fonctionner, version 2.3.3.
Contenu encrypté ne peut être joué (cana Évasion, Van Aventure).
La chaine en direct fonctionne.

**Comment by anisite** [comment]
@marseneault est-ce que le plugin est encore supporté ?

**Comment by marseneault** [comment]
Ça fait maintenant plusieurs années que je n'ai plus de compte Illico, n'étant plus client Vidéotron.  De plus, vu la migration de Illico vers une méthode d'encryption qui semblait impossible à contrer avec Kodi à l'époque, je ne sais pas si c'est possible de réparer le plugin aujourd'hui.

Le plugin n'est donc plus supporté.

**Comment by anisite** [comment]
Merci ! @marseneault
