### ISSUE TITLE
Noovo ne fonctionne plus

### ISSUE THREAD

**Issue by Sphinxroot** [anisite/DepotQuebec#53]
sources FB : Stephane Vallieres On a mis le site à jour jeudi passé. Changement de look et de champs titres et description pour les vidéos. Alors ils devront changer le plugin jimagine. Je sais pas qui développais ça... sorry

**Comment by kevint277** [comment]
@anisite

**Comment by anisite** [comment]
La version 0.6.2 corrige le problème, merci!
