### ISSUE TITLE
TV5Unis 

### ISSUE THREAD

**Issue by jo90quebec** [anisite/DepotQuebec#54]
Bonjour , d’abord un gros merci ! Ce serait bien de retrouver un addiciel pour le site TV5Unis, c’est dans vos plans ?

**Comment by dualB** [comment]
Bonjour! Si vous êtes intéressés à le développer, nous encourageons toutes les initiatives. Personnellement, je n'ai pas de temps libres pour m'y pencher.

**Comment by jo90quebec** [comment]
Ok je comprends. Malheureusement je n’ai pas les compétences, c’était une question.

**Comment by dualB** [comment]
Il n'y a pas de développeur pour TV5Unis, l'additiel sera retiré.
