### ISSUE TITLE
Tou.tv : A-Z list stop a la lettre L

### ISSUE THREAD

**Issue by rikkyprimo** [anisite/DepotQuebec#56]
Bonjour ! 
Petit bogue du coté de l'addi Tou.tv. La liste d'émission de A-Z arrête a la lettre L.
Merci de regarder ça ! Excellent travail :)

**Comment by anisite** [comment]
Est-ce encore d'actualité ?

**Comment by MartChic** [comment]
Oui !

**Comment by anisite** [comment]
Désolé j'ai dormis au Gaz... trop de travail pour la pandémie ... bref... ça semble corrigé ?!?

**Comment by rikkyprimo** [comment]
Oui ça c'est replacer. Merci pour le suivi :)
