### ISSUE TITLE
Télé-Quebec - Erreur de lecture

### ISSUE THREAD

**Issue by rikkyprimo** [anisite/DepotQuebec#60]
Bonjour ! De plus en plus d'erreur de lecture ( refus de lire la vidéo) avec le contenue de Télé- Quebec.  Par exemple Le bal mammouth marche bien sur le site web mais Kodi refuse de le lire. Ceci est un exemple parmis tant d'autre. Si vous pouvez vérifier ce serait gentil :) MERCI !

**Comment by dualB** [comment]
TQ utilise oscille entre Brightcove et Limelight. Et l'information n'est pas disponible au même endroit. Je vais voir ce que je peux faire.

**Comment by rikkyprimo** [comment]
C'est gentil! Merci beaucoup pour le suivi!

**Comment by rikkyprimo** [comment]
Bonjour ! Je voulais savoir si vous avez eu la chance de trouver une solution. J'aimerais aussi contribuer un peu financièrement pour le temps que vous investissé . Vous faite vraiment un travail de pro!!!!  Merci !

**Comment by dualB** [comment]
On n'a pas besoin d'argent.
N'étant pas un codeur professionnel, je ne parviens pas à effectuer les requêtes nécessaires pour lire le contenu provenant exclusivement de Brightcove. D'ici à ce quelqu'un d'autre soit en mesure de m'aider à y parvenir, il n'y a pas grand-chose que je puisse faire pour l'instant.

**Comment by anisite** [comment]
avez-vous un exemple de vidéo uniquement Brightcove?

**Comment by dualB** [comment]
Exemple : 
https://zonevideo.telequebec.tv/media/55219/avec-qui-tu-vas-au-bal/le-bal-mammouth-2020
Les infos de stream se retrouve ensuite ici : 
https://mnmedias.api.telequebec.tv/api/v4/player/55219
Puis on doit récupérer le fichier .m3u8 avec l'URL suivant (qui se sert du "sourceId") : 
https://bcovlive-a.akamaihd.net/86e93a0ab79047e1b216e2b0a1ac5363/us-east-1/6165835658001/playlist.m3u8
Ça fonctionne si j'ai précédemment navigué via le site web, mais pas via Kodi.

**Comment by dualB** [comment]
La nouvelle version TQ 3.3.0 va maintenant supporter les lien Brightcove.
