### ISSUE TITLE
Telequebec sur Ubuntu 

### ISSUE THREAD

**Issue by Kkeven125** [anisite/DepotQuebec#63]
Bonjour, il semble que l'addon Telequebec ne s'installe pas sur Ubuntu. Les autres s'installent sans problème. Je vous joint mon log à cet adresse : https://paste.kodi.tv/esoquyeviq. Ca dit ce message d'erreur :  the dependency on inputstream.adaptive version 1.0.8 could not be satisfied.

merci pour votre bon travail :)

**Comment by dualB** [comment]
As-tu tenté d'installer manuellement la dépendance ? Elle se trouve sur le repo officiel de Kodi.

**Comment by Kkeven125** [comment]
Oui j'ai regardé dans le repo officiel, mais je ne l'ai pas dans la liste. Pourtant sur PC et sur android je l'ai dans la liste. Ce pourrait-il que ce soit parce que sur Ubuntu c'est la version 18.6 de Kodi qui est la dernière, tandis que sur PC c'est 18.8? Est-ce que je pourrais installer manuellement ce inputstream.adaptive à partir d'un fichier zip?

**Comment by dualB** [comment]
Le problème est-il réglé?

**Comment by Kkeven125** [comment]
Non je n'ai pas réussi à le régler

**Comment by dualB** [comment]
Ce plugin existe depuis longtemps, tu es sûrement en mesure de trouver l'information pour l'installer : 
https://kodi.wiki/view/Add-on:InputStream_Adaptive
https://github.com/peak3d/inputstream.adaptive

**Comment by Kkeven125** [comment]
J'ai réinstallé Kodi manuellement plutôt qu'avec le app store et maintenant j'ai la version 18.8. Tout fonctionne maintenant
