### ISSUE TITLE
Possibilité de télécharger?

### ISSUE THREAD

**Issue by lefoy** [anisite/DepotQuebec#64]
Premièrement merci pour ce repo, j'ai été capable d'écouter certains épisodes que je voulais regarder sur Tou.tv. Est-ce qu'il est possible à partir de Kodi ou autre de télécharger les épisodes? J'aimerais les avoir sur un disque dur mais je n'ai rien trouvé qui fonctionne avec Tou.tv jusqu'à présent

**Comment by dualB** [comment]
Bonjour, nos additiels n'offrent pas ce genre d'option.
