### ISSUE TITLE
Module dans  Depot Québec ne veulent pas se télécharger

### ISSUE THREAD

**Issue by Ricbla614** [anisite/DepotQuebec#65]
Lorque que je suis dans Kodi et que je veux isntaller un addiciel de Depot Québec, toutes les isntallations échoue. J'ai un systême android et j'ai ouvert le fichier zip avec kODI et acun additionnel ne permet le téléchargement et me  retourne le message d'échec. Le fichier zip que j'ai utilisé est le suivant:  repository.depot.quebec-1.0.0. Avez vous des solutions.

Merci et bonne journée

**Comment by dualB** [comment]
Bonjour, veuillez utiliser une version plus récente.
https://github.com/dualB/DepotQuebec/blob/master/repository.depot.quebec/repository.depot.quebec-1.6.0.zip?raw=true
