### ISSUE TITLE
Telechargement...

### ISSUE THREAD

**Issue by kebekois** [anisite/DepotQuebec#67]
Vue que vous avez trouvé comment enlever le DRM a la lecture, est-t'il possible de mettre une option de téléchargement dans le plugin de tou.tv ? merci

**Comment by dualB** [comment]
Nous n'offrons pas ce genre de fonctionnalités.

**Comment by anisite** [comment]
Effectivement, c'est une fonctionnalité souvent demandée, mais bien que la plupart des addons doivent déjà violer quelques règles des diffuseurs, nous avons toujours préférés ne pas inclure ce genre de chose, la plupart des licences sont payés en prévision que le contenu est distribué de façon éphémère. Une ligne qu'on ne franchira pas. Libre à vous de modifier le code à votre goût.
