### ISSUE TITLE
Tele-Quebec 3.4.1 Probleme nouveaux episodes

### ISSUE THREAD

**Issue by sylgrenier** [anisite/DepotQuebec#69]
Bonjour, Premièrement merci a tous ceux qui prennent le temps de fabriquer ces add-ons, dont je met sers a tous les jours.

J ai un problème avec le add-on de tele-quebec, c est comme si les nouveaux episodes ne sont a jour.
EX: Dans les media.  Sur le add-on, il n y a pas les derniers episodes.

Meme choses pour plusieurs autres.  J ai la version 3.41.

Merci  :-)

**Comment by anisite** [comment]
Je crois que c'est lié au nouveau site. je ne peux pas confirmer pour le moment de date de vérification.

**Comment by dualB** [comment]
Je suggère pour l'instant d'utiliser la nouvelle plateforme/application de Télé-Québec, qui facilite grandement la diffusion de son contenu web (il était temps..).

**Comment by primoop** [comment]
Au sujet de la nouvelle plateforme/application de Télé-Québec officiel, elle fonctionne que sur quelques appareils comme la Firestick et Chromecast Google TV. Malheureusement, elle ne fonctionne pas sur la 2019 NVIDIA Shield Android TV Pro et du coup je ne peux pas utiliser. On en a parlé sur le groupe facebook "CoupeZ le CABLE".

Le pourquoi que je préfère utiliser la version Dépôt Québec sur KODI. Effectivement, je me suis aperçu du même soucis mentionné ci-haut.

**Comment by anisite** [comment]
@primoop normalement la Shield a un chromecast intégré, je ne vois pas pourquoi tu ne pourrais pas "caster" sur la shield à partir d'un appareil mobile?

**Comment by primoop** [comment]
L'installation de l'application ce fait, mais une fois la vidéo choisi et appuyez sur lecture, le cercle de loading demeure à l'infini, le vidéo ne démarre jamais. J'ai vider mon cache, effacer les donner... bref malgré que je suis fort habile avec une Shield et Firestick, l'appli n'a vraiment pas marché. Semble-t-il ça marche pour la version 2017 selon mes échanges, mais personne avec la même Shield 2019 que moi ne s'est manifester pour me dire si le soucis ils l'ont aussi ou pas. Et le soutien technique de Télé-Québec m'a dit que la 2019 NVIDIA Shield Android TV Pro n'est pas compatible avec leur application. Jusqu'à ce que je trouve le truc qui glich, en entendant dommage que ça ne marche pas pour moi. Le pourquoi que je tiens à votre appli Dépôt Québec pour Télé-Québec. 

Je ne mélange pas mon appareil mobile et Shield, j'ai payé la Shield Pro pour son efficacité, popularité, son prix, on s'entendrait à que ce les applis y marche. En tout cas, pour le moment, je deal avec le fait que ça ne marche pas.

**Comment by anisite** [comment]
Je suis entrain de regarder pour faire quelque chose avec Tele-Quebec, ça devrait être faisable mais il faut que je prenne le temps.
