### ISSUE TITLE
Problème avec version 2.1.3 (fin juillet 2017)

### ISSUE THREAD

**Issue by durezeric** [anisite/DepotQuebec#7]
Allo
ILLICOWEB ne marche plus sur Kodi....   avez vous une nouvelle version en cours ?

**Comment by dualB** [comment]
Es-tu certain de ton numéro de version? La plus récente est la 2.1.3.

**Comment by durezeric** [comment]
Allo

Oui vous avez raison 2.1.3.  Désolé de la confusion 
Sur Kodi 17.3 git:20170524-147cec4. 

Depuis la semaine passé cela ne marche plus. 


Envoyé de mon iPhone

**Comment by marseneault** [comment]
L'authentification au portail web de Illico a changé la semaine dernière.  Problème corrigé dans la version 2.2.0 maintenant disponible dans le dépôt.
