### ISSUE TITLE
TVA 1.0.5 bug

### ISSUE THREAD

**Issue by BassLortie** [anisite/DepotQuebec#70]
Bonjour

Il semblerait que les nouveaux épisodes de l'hiver 2021 n'apparaissent plus dans l'addon TVA.

Ça semble être depuis que TVA on changé leu site Web pour ''https://www.qub.ca/tvaplus/tva''

Merci et bonne journée

**Comment by anisite** [comment]
@MaximeLussier est-ce que tu regarde ça ? Tu as du temps ?

**Comment by MaximeLussier** [comment]
@anisite Ouais, à temps perdu, un de mes collegues aide aussi

**Comment by anisite** [comment]
@BassLortie j'ai déployé une alpha de TVA, compatible avec le nouveau site et Kodi 19.
