### ISSUE TITLE
IllicoWeb brisée =[

### ISSUE THREAD

**Issue by jeasimon** [anisite/DepotQuebec#72]
Bonjour,

En premier je tiens à dire merci à l’ensemble des bénévoles qui permettent de rendre ce projet vivant!

Ma conjointe et moi-même avons mis un terme définir au câble depuis 1 an déjà grâce à ce dépôt.

Comme vous le savez, Kodi 19 est arrivé et il a pas mal écorché le projet au passage...

J’utilisais jusqu’à tout récemment  IllicoWeb (un proche m’a partagé ses acces Web) sur Kodi qui lui se retrouve sur un Android Box. Je ne suis malheureusement pas en mesure de downgrader Kodi 19 vers 18.

Si jamais vous avez un petit instant pour y jeter un coup d’œil, ça serait grandement apprécié!

PS : Oui c’est vrai je peux utiliser l’app mobile IllicoWeb mais elle est plus contraignant pour caster sur la tv... 

Merci encore une fois !

**Comment by anisite** [comment]
Bonsoir, merci de l'intérêt, par contre, celui qui s'occupait de l'addon n'est plus en mesure de le développer, puisque qu'il n'a plus d'abonnement illico, c'est la même chose pour moi, même si je voulait, sans compte... impossible à tester. Ça me surprend honnêtement que l'addon fonctionne encore...voir: https://github.com/anisite/DepotQuebec/issues/52

**Comment by jeasimon** [comment]
Ok merci encore pour avoir pris le temps de me répondre !

**Comment by anisite** [comment]
@jeasimon si jamais je met la main sur un compte je vais regarder ça.
