### ISSUE TITLE
Noovo ne fonctionne plus

### ISSUE THREAD

**Issue by rikkyprimo** [anisite/DepotQuebec#74]
Bon matin ! 
Merci pour votre excellent travail. Un petit pépin ce matin: 
Noovo  Semble mort.
Si vous avez du temps pour regarder ça ce serait super ! 
Merci !

**Comment by primoop** [comment]
De mon côté TVA fonctionne correctement sur Kodi 19. J'ignore pourquoi moi ça marche et vous non.

Noovo ne fonctionne plus car le site web a été revampé par Noovo pour y inclure Canal D, Investigation, Canal Vie, etc.

Je ne suis pas un membre de l'équipe mais comme vous un utilisateur de Dépot Quebec. Comme vous savez, l'équipe fera de son mieux en temps libre (c'est du bénévolat) pour voir ça.

**Comment by rikkyprimo** [comment]
Suivi: Oui de mon coté TVA est revenue aussi :) Ne reste que Noovo si possible. Je sais que c'est fou le travail que ca demande quand il changeurs leur site web.

**Comment by anisite** [comment]
Bonjour, il a été décidé par moi et dualB de ne plus entretenir les addons, la dernière fois j'ai fais les changements pour supporter Kodi 19 à contrecœur, croyant donner un autre souffle à l'addon, mais les sites ont fait des mises à jour. Quand les addons ont été créés il n'y avait aucun bon moyen d'écouter les émissions sur sa télévision, depuis toutes les chaines ont rendu disponible une application mobile avec le support de Chromecast (Noovo, Téléqubec, ici tou.tv, même TVA) il n'y a donc plus de réelle raison de supporter un addons tierce partie.

**Comment by dualB** [comment]
Les chaînes québécoises ont su, aux cours des dernières années, rattraper leur retard quant à la diffusion de leur contenu sur le web. Personnellement, Kodi ne m'est plus nécessaire pour accéder à ces divers contenus vidéos; je n'ai donc plus aucune raison qui me motiverait à en faire l'entretien ou la mise à jour.

**Comment by Poopok257** [comment]
C'est bien dommage que vous laissiez tombé le projet. J'utilise vos additiels quotidiennement. L'avantage de vos additiels sont qu'il n'y a pas de publicités tous le temps comme avec les appli courantes. Toutefois, je comprend l'ampleur du travail pour mettre à jours ces addiciels. Merci pour ces années de bénévolat.

**Comment by dualB** [comment]
Les publicités, c'est ce qui permet aux diffuseurs de t'offrir du contenu gratuit et des plateformes à la fine pointe de la technologie.

**Comment by primoop** [comment]
Je comprend votre décision mais vu que les chaîne TV de TVA, Noovo entre autre, non pas encore offert d'application officiel pour: Firestick, Nvidia Shield, Apple TV, Chromecast, Roku, bref DépotQuébec était encore essentiel.
Télé-Québec vient de lancer leur application, elle marche sur Firestick, mais elle ne marche pas sur la Nvidia Shield Android TV Pro, du coup, je n'y ai pas accès, et je ne suis pas un novice avec la Nvidia Shield et Firestick.

J'aurais patienté encore 1 année le temps que TVA, Noovo et Télé-Québec offre leur application opérationnel sur Firestick, Nvidia Shield, Apple TV, Chromecast, Roku. Seulement à ce moment là, il n'y aurait plu de raison que votre DépotQuébec existe.
Pour moi, elle était très pratique et très utilisé DépotQuébec à ce jour. Maintenant, je ne peux que utiliser celle de TVA sur Kodi. Pour Noovo et Télé-Québec, je devrai aller sur mon ordi.

Mais comprenant que votre bénévolat de passion a une fin, bien je comprend que vous ayez d'autres priorités. Je vous remercie des efforts des dernières années sur DépotQuébec et de vos retours en messages rapide, merci.

**Comment by kanigouvalley** [comment]
Merci pour toutes ses années de travail, vos explications apportent tout le sens de votre décison. Depot Quebec etait assurement une des fiertées francophones sur Kodi a mon avis. Au plaisir de vous revoir ailleurs pour peut etre un autre projet!

**Comment by boiss** [comment]
Merci pour votre excellent travail au cours des dernières années @dualB et @anisite !

**Comment by sansillusion** [comment]
C'est désolant mais comprenable. Juste plate car c'était ma seule façon d'écouter noovo, j'utilise un rpi4 avec kodi (libreelec) je n'ai pas de Chromecast ou autres et mon laptop est mourant. Mais je n'ai ni le temps ni les compétences de le faire moi même. Alors je vous dit sincèrement un gros merci pour toutes ces années de votre bon travail.

**Comment by etogaman** [comment]
Il y a t il possibilité de continuer votre projet ? J veux dire qu une autre personne puisse le continuer à votre place ?

**Comment by boucchar** [comment]
Bonjour et merci beaucoup pour votre travail plus qu'excellent. Je suis en deuil sérieusement, nous utilisons vos addons dans notre quotidien. J'abonde dans le même sens que le message précédent, est ce possible pour vous de cibler des développeurs interressé à continuer le projet? Admettons que vous ayez des contacts dans votre domaines? Merci encore!

**Comment by alKODIque** [comment]
@anisite 
@dualB 

Je voulais prendre le temps de vous remercier d'avoir mis tout votre temps et énergie dans le développement et le maintient de ce seul addon (plutôt dépôt) québécois que nous avions pour kodi.

Je comprends bien tout le travail que ça représente et je comprend également votre décision...

Dans tous les cas, merci encore et au plaisir de peut-être vous retrouver ailleurs, dans de nouveaux projets, qui sait!! ;)

**Comment by anisite** [comment]
Une version 3 a été livrée ce PM, est-ce que ça fonctionne de votre bord?

**Comment by sansillusion** [comment]
Oui sa marche ! Merci beaucoup !
Direct et sur demande.
Librelec 10.0

**Comment by sansillusion** [comment]
Certaines émissions semble ne pas fonctionner comme "Comédie sur mesure"
mais d'autres fonctionne très bien comme "Open mic de..." et le direct
aussi. C'est déjà très biens.

**Comment by anisite** [comment]
@sansillusion J'ai livré une version 3.0.4 je crois que ça corrige les émissions qui n'étaient pas fonctionnelles

**Comment by sansillusion** [comment]
Merci.
Je vais essayer demain.

Le mar. 7 sept. 2021 8 h 08 p.m., anisite ***@***.***> a
écrit :

**Comment by alKODIque** [comment]
@anisite 
Super! Merci d'avoir informé :)
Je vais vérifier 

Heureuse d'avoir des nouvelles ;)

**Comment by alKODIque** [comment]
Ça fonctionne bien pour moi 🙂

Je remarque un petit souci de rien du tout au niveau de l'affichage du titre pour la section en direct, et au niveau de la description des émissions. (voir encadrés rouges sur impressions d'écran)

Mais sinon, tout est super 👍
Grand merci pour votre travail!

![plot](https://user-images.githubusercontent.com/49578130/132434216-6ca5ed83-2a6e-468e-a2b2-f60548e2f0a4.png)
![titre](https://user-images.githubusercontent.com/49578130/132434218-54ee8b73-91d0-4c26-8a71-6cc64a3f7225.png)

**Comment by anisite** [comment]
Bonjour, oui le bug a été remarqué sur Kodi 19.1 mais ce n'est pas encore priorisé, un changement pourrait faire planter Kodi 18.9 alors je vais devoir faire plusieurs tests, c'était le compromis pour pouvoir livrer quelque chose...

ps. il est étrange votre skin, il met le fanart en tant que image de l'émission... normalement ça va en background... en tout cas!

**Comment by alKODIque** [comment]
> ps. il est étrange votre skin, il met le fanart en tant que image de l'émission... normalement ça va en background... en tout cas!

Ca dépends du type de vue choisi.. 
Mon skin propose différents types de vues si le média est identifé selon les critères TMDb dans le code de l'addon utilisé, (soit un film, saga, une série, une saison ou un épisode)

.. ici les types de vue proposées sont celles pour les épisodes télé. Celle faisant l'objet de ta remarque concerne ''l'affichage en rangée fanart'', mais il y a plus d'un choix par type de média)

Si on ne voit rien en back ground sur la section en direct, c'est qu'il n'y a pas de fanart pour la visualisation à la base pour cet écran (en bleu). 

Mais si je me déplace,  on voiit bien le fanart et j'ai même droit a un joli clearart lorsque fanart.tv en trouve pour le titre affiché 😉 comme c'est le cas pour Twilight Zone dans Ici tou.tv
**[ - Skin Arctic Horizon](https://github.com/jurialmunkey/skin.arctic.horizon)**

![Screenshot_20210907-221923](https://user-images.githubusercontent.com/49578130/132436275-6f8a1131-0c53-4c1c-9b18-949280be1992.png)

**Comment by alKODIque** [comment]
Je crois que l'identification selon les ientifiants TMDb n'est peut-être pas réalisable avec des addons qui nécessitent l'usage de DRM (comme Tou.Tv) ... 
Je sais pas trop, miais l'addon kodi Netflix propose ses propres Poster, fanart et affiches Landscape.. et semble tirer ses informations,synopsys et autres directement depuis Netflix et non selon les standards TMDb

![Screenshot_20210907-223248](https://user-images.githubusercontent.com/49578130/132437317-322c24b5-2a1d-495e-9f31-cc8011a662bd.png)

**Comment by durang0** [comment]
Bonjour premièrement merci de tenir les add-on en fonction c'est très apprécié.

J'ai un problème avec le addon vtele  j'obtiens dans les logs ceci.

ERROR : EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'IndexError'>
Error Contents: list index out of range
Traceback (most recent call last):
File "/home/osmc/.kodi/addons/plugin.video.vtele/default.py", line 132, in 
peupler()
File "/home/osmc/.kodi/addons/plugin.video.vtele/default.py", line 28, in peupler
creer_menu_categories()
File "/home/osmc/.kodi/addons/plugin.video.vtele/default.py", line 36, in creer_menu_categories
navig.ajouterItemAuMenu(content.dictOfGenres(filtres))
File "/home/osmc/.kodi/addons/plugin.video.vtele/resources/lib/content.py", line 230, in dictOfGenres
'image' : carte['posterImages'][0]['url'],
IndexError: list index out of range
-->End of Python script error report<--

En fait a premiere vu le plugin ne semble plus être capable de récupérer les images et fanart.  

Merci.

**Comment by erikatremblay** [comment]
Même chose ici noovo ne fonctionne plus il n’ouvre plus du tout 😔

**Comment by durang0** [comment]
Bonjour pour l'instant en attendant un possible update il est possible de remettre en fonction sans les images et fanars en commantant les lignes suivantes (ajoutant un # devant les lignes en question) directement dans les fichiers du plugin.

Ensuite le plugin va partir de nouveau mais ce mettre en visualisation liste car sinon vous ne verrez plus rien.

addons/plugin.video.vtele/resources/lib

dans le content.py
----# 'image' :  carte['posterImages'][0]['url'],
----# 'fanart':  carte['thumbnailImages'][0]['url'],
----# item['image'] = item['image'] or xbmcaddon.Addon().getAddonInfo('path')+'/resources/icon.png'
----# item['fanart'] = item['fanart'] or xbmcaddon.Addon().getAddonInfo('path')+'/resources/fanart.jpg'

aussi dans le fichier navig.py

--- # iconimage =show['image']
--- # fanart = show['fanart']
--- #  if iconimage=='':
--- #  iconimage = ADDON_IMAGES_BASEPATH+'default-folder.png'
--- # liz = xbmcgui.ListItem(nom,iconImage=iconimage,thumbnailImage=iconimage)
--- # liz.setArt({ 'thumb' : iconimage } )                                  
--- # liz.setArt({ 'poster' : iconimage } )                                
--- # liz.setArt({ 'fanart' : fanart } )
