### ISSUE TITLE
Incapable d'ouvrir l'Addon

### ISSUE THREAD

**Issue by SPYR0999** [anisite/DepotQuebec#75]
Après avoir installé Dépôt Québec dans Kodi, je ne le trouve dans aucun menu et si je tente de l'ouvrir via la liste d'Addon, le bouton Run est grisé et inactif.

Savez-vous pourquoi ça fait ça?

Je suis sur Kodi 18.9.

**Comment by SPYR0999** [comment]
Je viens de réaliser qu'il faut aller télécharger les services a partir du repository. J'ai toutefois des messages d'erreur lorsque je tente d'installer.
Quelle taille sont les Addons avec toutes leurs dependencies?

**Comment by anisite** [comment]
@SPYR0999 avez-vous trouver ?

**Comment by SPYR0999** [comment]
@anisite

Certains des composantes nécessaires pour que dépôt Québec fonctionnent ne run que sur la version Windows de Kodi...

Dépôt Quebec n'est pas compatible avec Linux.

**Comment by anisite** [comment]
Avez-vous un exemple de composante ? Parce que normalement Dépot Québec c'est juste un dépot et les addons normalement sont compatible (ex: noovo fonctionne sur OpenElec)

**Comment by SPYR0999** [comment]
Je ne m'en rappelle plus vraiment et j'ai démonté mon système Kodi...
Je me rappelle qu'il fallait installer quelque chose qui utilise des libraries Windows pour fonctionner.

**Comment by anisite** [comment]
parfait je vais fermer par manque d'infos, merci!
