### ISSUE TITLE
Tou.Tv ne fonctionne plus 

### ISSUE THREAD

**Issue by BassLortie** [anisite/DepotQuebec#78]
Bonjour

Tou.tv ne semble plus fonctionner depuis quelques jours (Kodi V19.1)

J'ai tester sur Windows, Android et Shield TV même erreur partout…

On dirait que c'est à cause d'un changement du côté de Tou.tv...??

**Comment by anisite** [comment]
oui ça été rapporté ici https://github.com/anisite/plugin.infologique.tou.tv/issues/26 je ne sais pas quand ça sera corrigé et si je vais pouvoir le corriger

**Comment by erikatremblay** [comment]
J’aimerais émettre un commentaire tou.tv fonctionne mais quand il n’y a pas de compte d’entré. aussitôt que nous mettons notre compte il cesse de fonctionner. J’ai remarqué que sur mon cellulaire tout a l’heure j’ai du me reconnecter et il était mentionné que tou.tv avait fait des changements dans la configuration de la connexion. Je crois que le soucis vient de là ;)

**Comment by MartChic** [comment]
Je pense que le problème est aussi du côté de Radio-Canada parce que ça ne fonctionne pas non plus avec Chromecast Ultra.

**Comment by anisite** [comment]
@erikatremblay  oui tel qu'expliqué ici hier : https://github.com/anisite/plugin.infologique.tou.tv/issues/26#issuecomment-927482262  @MartChic j'ai utilisé ce midi sans prob. avez-vous refaire la connexion dans l'app?

**Comment by MartChic** [comment]
Hier il a fallu que je désinstalle et réinstalle pour que ça fonctionne dans Chromecast (Google tv). J'ai réessayé ce soir et ça ne fonctionnait plus.

**Comment by MartChic** [comment]
> Hier il a fallu que je désinstalle et réinstalle pour que ça fonctionne dans Chromecast (Google tv). J'ai réessayé ce soir et ça ne fonctionnait plus.

Tou.tv sur Google Tv est revenu à la normale aujourd'hui.

**Comment by anisite** [comment]
Je viens de livrer la version 5.1.0 avec le nouveau login, ça fonctionne sur Kodi 19 pas eu le temps de tester 18 encore ! Dites-moi si ça marche.

**Comment by BassLortie** [comment]
Oui ça fonctionne bien sur Kodi 19.
J'ai testé sur cellulaire Android, shield tv, Google Chromecast tv et sur pc.
Good job merci!!

**Comment by anisite** [comment]
@BassLortie  merci!

**Comment by g4pos** [comment]
Merci, ça marche parfaitement

**Comment by boucchar** [comment]
Merci! Fonctionne #1 sur Kodi 18.7 sur RPI4. Par contre il faut absolument upgradé RPI OS de Buster vers BullsEye car inputstream helper n'update plus le DRM si c'est Buster.
