### ISSUE TITLE
Update vers Kodi 19

### ISSUE THREAD

**Issue by mo418** [anisite/DepotQuebec#79]
Bonjour
CECI N'EST PAS UNE "ISSUE" MAIS PLUTÔT UNE QUESTION! :) (je ne savais pas quelle section choisir pour la poser)

J'ai vu que vous aviez travaillé un peu sur le projet malgré votre annonce de fin de support il y a quelques semaines. 

Est-ce que le passage à Kodi 19 implique que certains addons ne fonctionneront plus ou avec les dernières mises à jour, le tout demeure fonctionnel? Je retarde l'update juste à cause de votre addon qui me permet de tout centraliser! 

Si certains utilisateurs pourraient me dire si c'est fonctionnel (ou pas), ce serait très apprécié également. 

Un gros merci d'avance, mais surtout pour le travail effectué!

**Comment by anisite** [comment]
Bonjour je crois que telequebec et Illico web ne fonctionnent pas actuellement sur Kodi 19. Ils ne sont pas non plus maintenus activement sur ce dépôt présentement, si un développeur veut se joindre à moi pour les entretenir pourquoi pas.

Donc les principaux mainstream tou.tv, tva et noovo fonctionnent pour ce qui est de dépôt Québec. J'ai mis la fin du support de 18.x pour la fin de l'année parce que je ne veux plus garantir un fonctionnement, Kodi 20 va arriver et à chaque version des améliorations du lecteur vidéo sont faites, ce qui est bien. Je ne peux pas parler pour les autres addons je n'en utilise pas d'autres.

**Comment by mo418** [comment]
Salut,

Parfait, merci pour le retour rapide et le suivi sur le dossier! Effectivement, ça serait vraiment bien qu'un développeur puisse se joindre à toi pour aider à maintenir le tout. Malheureusement, je n'ai pas les connaissances.

Encore une fois merci et bonne fin de journée!

**Comment by The-NinthWave** [comment]
Moi et certainement d'autres personnes seraient heureuses qu'il y ait un maintien des addiciels.

Je comprends l'argument des développeurs concernant les sites et applications des télédiffuseurs compatibles Chromecast, mais il y a aussi une communauté pour CoreElec (Kodi installé _baremetal_ sur une boite média ou un SBC).  Sans Android, on oublie les fureteurs internets et les applications chromecast.  Pour la communauté CoreElec, vos additiels autonomes sont une bénédiction.

J'ai une boite avec CoreElec 6 (Leia) et l'addiciel autonome Télé-Québec, qui fonctionne toujours très bien, est très supérieur à l'onglet intégré dans Tou.TV.

Je suis même prêt à faire un virement paypal si ça peut inciter les développeurs à s'y remettre.

Peut importe la décision, merci d'avoir créé ces additiels.
