### ISSUE TITLE
illicoweb ne demarre pas

### ISSUE THREAD

**Issue by Cleanfabric** [anisite/DepotQuebec#8]
Dernièrement, jai mis à niveau mon Kodi de 15 a 17.3. Tout fonctionnait à merveille avec l'ancienne version de Kodi. Une fois à 17.3 ça ne fonctionnait plus. Vu que je ne l'avais pas effacé encore, j'ai uninstall/install à nouveau. Joie!!! Ça' fontionné... une seule fois.

Donc maintenant, chaque fois que j'essaie de le démarrer, ça fait un erreur et ça dit de vérifier les logs.  J'ouvre les logs et il n'y a rien! Pas de crash report du tout. Cest comme si Kodi n'a même pas essayé de le partir.
Merci pour tout le travail que tu fais.

**Comment by marseneault** [comment]
Pourrais-tu activer le déboggage du addiciel (dans les paramètres de IllicoWeb) et essayer de nouveau?  Lorsque tu auras eu l'erreur, va voir ton kodi.log.

**Comment by Cleanfabric** [comment]
Parfait! Je vais essayer ca en arrivant ce soir.



________________________________

**Comment by Cleanfabric** [comment]
Voici le log que je suis aller chercher.
https://paste.ubuntu.com/25266903/
J'ai réessayé d'ouvrir illicoweb avant de récupérer le .log

Je ne suis pas aller voir manuellement dans les fichier via mon ordinateur ce soir, par contre.

Si c'est préférable, je le ferai demain.

Merci pour votre temps.

Olivier.
________________________________

**Comment by marseneault** [comment]
Ton log est malheureusement incomplet.

**Comment by Cleanfabric** [comment]
Bonsoir à vous,

Je suis désolé du délais de retour. Je n'avais pas le temps de ressortir mon Log.
Bref.

Étant donné que je ne sais pas si le log est complet encore une fois (parce que j'ai trouvé une autre methode pour "paster" ledit fichier.
J'ai également sorti le fichier .zip de mon Pi, après avec fait quelques tentatives.


http://sprunge.us/JSFM


Il m'est passé pas la tête de faire un hard reset de mon LibreElec. Ça pourrait toujours fonctionner.

Des fois, c'est avec du recul qu'on a de bonnes idées


Sur ce, je vous souhaite une bonne soirée et merci encore.


Olivier.


________________________________

**Comment by marseneault** [comment]
Ton dernier log n'est pas un kodi.log.

Je sais que LibreElec éprouve quelques problèmes avec les addiciels qui nécessitent une connexion SSL à des sites https, comme c'est le cas avec IllicoWeb.  J'ai déjà cherché une solution dans le passé mais sans succès.  Je n'ai pas une boîte LibreElec pour faire plus de tests et comme je ne sais pas quelle erreur tu éprouves exactement je n'ai pas de pistes pour le moment.

Quand j'aurai ton log, je pourrai faire plus de recherches.

**Comment by Cleanfabric** [comment]
Bonsoir.
Suite a botre courriel me.disant que libreelec eprouvait des problemes, jai decidé d'essayer OSMC.

Jai passé quelques heures à tout mettre en place. Arrivé au moment de verité, j'inscrit mon username et password et je pars l'additiel.

Encore une fois, ca fait la même chose. Le kodi log est beaucoup plus long que les derniers.
Alors, le voici.

https://paste.osmc.tv/pejuficali

En esperant que ca fonctionne cette fois.

Merci pour votre temps.

Olivier.
________________________________

**Comment by marseneault** [comment]
Olivier,

Je ne sais pas si le problème persiste pour toi avec la version 2.3.2.  Si oui, est-ce que tu peux ouvrir un nouvel incident et joindre de nouveau ton kodi.log?

Merci!

**Comment by Cleanfabric** [comment]
Bonjour à vous,


Je n'ai pas fait la mise à jour de la version 2.3.2

Ce soir, je vais m'en occuper et vérifier si ça fonctionne.


Merci!


________________________________

**Comment by Cleanfabric** [comment]
Ça' fonctionné!

J'ai du reconfirmer mon nom d'utilisateur et mon mot de passe, parce que ça n'avait pas fonctionné du premier coup.

Cependant, apres le 2e essaie, tout était en ordre.

Merci beaucoup.



________________________________
