### ISSUE TITLE
Lag avec toi.tv

### ISSUE THREAD

**Issue by jerga16** [anisite/DepotQuebec#81]
Salut gang. Est ce que vous avez des trouble de lecture avec tou.tv. toujours en buffering

**Comment by boucchar** [comment]
Salut, j'ai eu ce problème. Je l'ai régler en restaurant la bibliothèque widevine a la version précédente. C'est dans les paramètres de inputstream helper.

**Comment by jerga16** [comment]
Salut merci de ta réponse. J'ai essayé mais rien y fait

**Comment by InFlamesHell** [comment]
j'ai le meme probleme.. 
Kodi 19 sur un rpi 4
Quelqu'un a d'autre idee que downgrade widevine? :)

**Comment by jerga16** [comment]
Je dois redémarrer avant d'écouter un épisode et ça fonctionne.

Le dim. 27 févr. 2022, 20 h 43, InFlamesHell ***@***.***> a
écrit :

**Comment by boucchar** [comment]
@InFlamesHell un downgrade temporaire en attendant la mise à jour de Anisite. À quoi peut bien servir un Widevine up to date s'il  cause des ennuis?

**Comment by InFlamesHell** [comment]
@boucchar , j'aurai du preciser.. l'ancienne version de widevine que j'ai fonctionne carrement pas. Erreur 400...
2022-02-28 19:35:46.602 T:613     ERROR <general>: CCurlFile::Open failed with code 400 for https://rcavtoutv-key.akamaized.net/Widevine/?KID=c1a9f14e-56e0-4d8d-bcbf-9b6e2594b247:

Avec la derniere version ca fonctionne mais ca buffer tout le temp... :(
tu connais une version qui fonctionne/buffer pas et ou je peu la trouver? :)

**Comment by boucchar** [comment]
@InFlamesHell voici ma version qui fonctionne. Dézip le fichier et copie le dossier CDM dans "/home/pi/.kodi" et reboot ton RPI
[cdm.zip](https://github.com/anisite/DepotQuebec/files/8163279/cdm.zip)

**Comment by InFlamesHell** [comment]
ca marche! merci bcp @boucchar

**Comment by MartChic** [comment]
> @InFlamesHell voici ma version qui fonctionne. Dézip le fichier et copie le dossier CDM dans "/home/pi/.kodi" et reboot ton RPI [cdm.zip](https://github.com/anisite/DepotQuebec/files/8163279/cdm.zip)

C'est quelle version ?

**Comment by MartChic** [comment]
J'ai trouvé cette discussion à ce sujet. On y parle entre autres de désactiver http2.

https://discourse.osmc.tv/t/unusable-constant-buffering-since-2021-12-1-latest-widevine/92209/53

**Comment by franckgaga** [comment]
Même problème ici sur RPi 3B+ Kodi 19 (libreelec). Le plugin Netflix fonctionne pourtant, qui utilise aussi les mêmes fichiers de widevine @anisite crois tu que tu peux regarder ça ? Merci!

**Comment by jerga16** [comment]
Même problème avec Amazon prime est ce que vous pouvez poussez l'update qui
fonctionne?

Le lun. 14 mars 2022, 20 h 07, franckgaga ***@***.***> a
écrit :

**Comment by anisite** [comment]
Salut, je ne peux pas corriger quelque chose que je ne contrôle pas, il faudrait regarder pour downgrade votre widevine avec la solution slyguy [https://github.com/CastagnaIT/plugin.video.netflix/issues/1321](https://github.com/CastagnaIT/plugin.video.netflix/issues/1321)

**Comment by franckgaga** [comment]
@anisite En effet, bon point! Merci pour la solution de slyguy, ça fonctionne bien maintenant !
