### ISSUE TITLE
Erreur avec tva plus

### ISSUE THREAD

**Issue by jerga16** [anisite/DepotQuebec#82]
Est ce que vous êtes capable de voir les séries sur tva plus? Moi ça me fait un erreur. Les autres (addik tv, tva sports fonctionne)

**Comment by boucchar** [comment]
Bonjour, même chose ici. Je suis sous Kodi 19.3 Rpi4 Os Bullseye

**Comment by KodiTopQuebec** [comment]
même chose ici , message pour les dev a quand un correctif pour tva ? , merci

**Comment by tatou100** [comment]
Même problème pour moi. J'ai fait un fix hier. J'essaie de contacter les admin puisque je n'ai pas accès à ce repo. 
J'ai mis mon fix ici en attendant si vous voulez essayer. https://github.com/tatou100/TVAgo/tree/bugfix/jsonStructureFix

@anisite @MaximeLussier Pouvez vous m'authoriser a pousser dans le repo de TVA?

**Comment by boucchar** [comment]
Merci. Le fix fonctionne parfaitement.

**Comment by jerga16** [comment]
Comment on fait pour appliquer le.fix....svp 🤷🏻‍♂️

Le dim. 27 févr. 2022, 18 h 57, boucchar ***@***.***> a
écrit :

**Comment by tatou100** [comment]
@jerga16 Le fix est maintenant déployé. Tu peux essayer de mettre à jour l'extension dans ton Kodi directement ou attendre. Il devrait se mettre à jour dans les prochaines heures
