### ISSUE TITLE
Télé-québec ne fait plus parti du dépot?

### ISSUE THREAD

**Issue by Poopok257** [anisite/DepotQuebec#83]
J'ai du réinstaller kodi. Après avoir dl le depotquebec 1.6 surprise ajout de crave et retrait de télé-québec...
J'ai essayé de dl le zip de laddon télé-québec mais impossible de l'installer. Avant de devoir réinstaller kodi, télé-québec marchait super bien ! Quelqu'un peut m'aider ? 

Merci

**Comment by MartChic** [comment]
Il y a quelqu'un qui travaille là-dessus.

https://github.com/dualB/plugin.video.telequebec/pull/22

**Comment by anisite** [comment]
Y a-t-il encore de l'intéret pour télé-québec ? est-ce qu'un version de l'addon est fonctionnel quelque part ?

**Comment by mo418** [comment]
Bonjour,
Il y a de l'intérêt ici pour une raison qui avait été évoquée je crois dans d'autres "issues". C'est bien de regrouper le tout dans Kodi, même s'il y a une app qui existe pour Télé-Québec. Il y a beaucoup d'émissions pour enfants également, pratique pour les jeunes parents :) Ce n'est que mon opinion, et merci pour ton travail pour soutenir cet addon. C'est plus qu'apprécié.

**Comment by anisite** [comment]
Télé-Quebec fonctionne sur Kodi 18 seulement, malheureusement la version 19 et n'a jamais été terminée j'ai une version qui marche à moitié sur mon ordi mais jamais eu de temps pour finir le début ca devient long et très Tannant de tester sur 18 et 20 en même temps, la migration des add-on brise le retour en arrière, je vais probablement faire une version Kodi 19-20 seulement cette semaine et arrêter le support de 18

**Comment by anisite** [comment]
Quelqu'un avec kodi 18 possède encore Télé-Québec ?? Est-ce que celui-ci fonctionne encore? J'essayais de migré à Python 3 mais ... on dirait que tout le site a changé. Est-ce possible ?

**Comment by anisite** [comment]
Fermé pour inactivité
