### ISSUE TITLE
Incapable de télécharger fichier zip

### ISSUE THREAD

**Issue by Coulombeo** [anisite/DepotQuebec#84]
Bonjour, lorsque je clique sur le lien "cliquez ici" un message du browser apparait "le téléchargement ne peut pas être effectué pour le moment" doit-on utiliser un navigateur en particulier?

Voici mes versions: 
Fire stick 6.2.9.2
Amazon silk 104.2.16.5112.114.30

**Comment by anisite** [comment]
Normalement le lien fonctionne, avez-vous réussi depuis ?
