### ISSUE TITLE
Meteo

### ISSUE THREAD

**Issue by nquesada** [anisite/DepotQuebec#85]
Prévisions météorologiques 

Bonjour tout le monde, je me demandais si l'un d'entre vous serait intéressé / connaîtrait des ressources sur la façon de faire un addon pour la prévision de la météo en utilisant les données fournies par https://meteo.gc.ca/canada_f.html . 

Sinon, merci beaucoup d'avoir créé ces addons, ils sont géniaux!

**Comment by anisite** [comment]
Bonjour, désolé, il n'y a pas d'intérêt pour ma part. Si quelqu'un veut le développer nous l'ajouterons avec plaisir.
