### ISSUE TITLE
Sous-titres

### ISSUE THREAD

**Issue by nquesada** [anisite/DepotQuebec#86]
Bonjour --- Je me demandais s'il serait possible d'ajouter la possibilité de lire les sous-titres déjà disponibles sur Radio-Canada dans l'add-on. Actuellement, cela ne semble pas être disponible.

**Comment by anisite** [comment]
Bonjour tout est possible mais probablement pas si simple, il faut ajouter le téléchargement des str et les inclure, je ne pense pas pouvoir faire ça prochainement malheureusement, si quelqu'un a un pull request à fournir je suis preneur
