### ISSUE TITLE
Kodi V20 

### ISSUE THREAD

**Issue by Michaeld506** [anisite/DepotQuebec#87]
Kodi 20 est sorti et le repo ne fonctionne plus

**Comment by anisite** [comment]
Bonsoir, le repo a été corrigé, il est possible qu'il ne se mette pas à jour tout seul, dans ce cas il faudra le retélécharger, pour le moment il y a juste ICI TOU.TV qui est fonctionnel je crois. SVP m'informer.

**Comment by anisite** [comment]
Tou.tv, TVA+ et NOOVO sont ajustés Crave je ne peux pas dire, mais semble OK

**Comment by Michaeld506** [comment]
> Tou.tv, TVA+ et NOOVO sont ajustés Crave je ne peux pas dire, mais semble OK

Merci beaucoup !!

**Comment by flingflang** [comment]
Bonjour. Grand merci pour les corrections. Très apprécié. Je roule Kodi sous Ubuntu 20.04.5 LTS. Je confirme qu'une réinstallation du ZIP est nécessaire. TVA fonctionne. Par contre Tou.tv affiche les menus correctement mais la video ne fonctionne pas. Dans les configurations du addon Tou.tv, le type de flux a utiliser est-il HLS, Widevine ou RTSP? J'ai testé les 3 sans succès (j'avais HLS d'activé au départ). Aussi faut-il désactiver les DRM? J'avoue avoir oublié... Merci!

**Comment by anisite** [comment]
bonjour, ces options devraient toutes être retirées elle ne servent plus dans le code, c'est mon erreur. mais est-ce possible de valider que vous avez bien InputStream Adaptative et InputStream Helper dans "all add-ons" d'installé et avez-vous eu le popup d'installation de widevine lors du démarrage d'un vidéo ? Aussi avez vous le log de kodi suite à une tentative de démarrage d'un vidéo ? merci

**Comment by flingflang** [comment]
Bonjour.  InputStream Adaptative et InputStream Helper sont présents et activés. J'ai réinstallé "widevine CDM Library" via : InputStream Helper > Configure > Expert > (Re)install widevine CDM Library. J'ai redémarré Kodi. Toujours pas de vidéo. Voici le contenu de mon kodi.log (suite au lancement d'une video) : https://paste.kodi.tv/ixicuzotug.kodi

**Comment by KodiTopQuebec** [comment]
suis-je le seul que ici tou.tv j'ai pas de son sous kodi 20 ? , si je change le flux pour 1/2 ca fonctionne mais c'est avec audio description , par défaut c'est le 2/2 , j'ai ce problème sur tout mes appareils

**Comment by KodiTopQuebec** [comment]
bon voici du nouveau pour vous informez du problème de son, lorsque je part un émission dans tou.tv et que j'ai pas de son  si j'avance de quelques secondes et son reviens normal , autre point parfois je part un émission et j'ai du son mais l'image est gèle donc même chose a faire avance de quelques secondes et tout est ok , suis-je le seul ?

**Comment by anisite** [comment]
Sur quel OS, équipement ?

**Comment by KodiTopQuebec** [comment]
nvidia shield OS v11, firestick 4k max le plus ressent OS , firestick 4k, pc windows 10, j'ai même essayé de supprimer le addon et faire l'installation a neuf sans rien de mieux , je ne suis pas le seul qui a ce problème un de mes amis a cela lui aussi et doit faire le petit truc de l'avance rapide

**Comment by Ricardodel** [comment]
Meme chose de Mon coté

**Comment by Ricardodel** [comment]
Sur android

**Comment by flingflang** [comment]
De mon côté il y a eu progression. Dans les dernières mise à jour Ubuntu, il y avait : kodi-inputstream-adaptive-6:20.3.2-1-focal.amd64. Je l'ai installé et là la video fonctionne. Par contre moi non plus je n'ai pas de son... En fait, j'en ai eu quelques secondes. J'ai lancé une video, je suis allé dans le menu (clavier : M) > Setting > Audio settings > Audio Stream. J'ai basculé le 2/2 vers 1/2 et là j'ai entendu la video description. J'ai rebasculé vers 2/2 : pas de son. Je suis revenu vers 1/2 : plus de son!? Depuis rien. J'ai pas de son peu importe. Mais la video fonctionne toujours.

**Comment by KodiTopQuebec** [comment]
> De mon côté il y a eu progression. Dans les dernières mise à jour Ubuntu, il y avait : kodi-inputstream-adaptive-6:20.3.2-1-focal.amd64. Je l'ai installé et là la video fonctionne. Par contre moi non plus je n'ai pas de son... En fait, j'en ai eu quelques secondes. J'ai lancé une video, je suis allé dans le menu (clavier : M) > Setting > Audio settings > Audio Stream. J'ai basculé le 2/2 vers 1/2 et là j'ai entendu la video description. J'ai rebasculé vers 2/2 : pas de son. Je suis revenu vers 1/2 : plus de son!? Depuis rien. J'ai pas de son peu importe. Mais la video fonctionne toujours.

fait mon petit truc dit plus haut et tu auras du son  et si tu as du son et que l'image gèle même petit truc , j ai hâte d'avoir une correction pour ce bug

**Comment by flingflang** [comment]
> > De mon côté il y a eu progression. Dans les dernières mise à jour Ubuntu, il y avait : kodi-inputstream-adaptive-6:20.3.2-1-focal.amd64. Je l'ai installé et là la video fonctionne. Par contre moi non plus je n'ai pas de son... En fait, j'en ai eu quelques secondes. J'ai lancé une video, je suis allé dans le menu (clavier : M) > Setting > Audio settings > Audio Stream. J'ai basculé le 2/2 vers 1/2 et là j'ai entendu la video description. J'ai rebasculé vers 2/2 : pas de son. Je suis revenu vers 1/2 : plus de son!? Depuis rien. J'ai pas de son peu importe. Mais la video fonctionne toujours.
> 
> fait mon petit truc dit plus haut et tu auras du son et si tu as du son et que l'image gèle même petit truc , j ai hâte d'avoir une correction pour ce bug

Et bien ça semble bien fonctionner en effet ton petit truc. J'avais pas porté attention à ton message considérant que je n'avais pas de video du tout..! La victoire est proche. Soyons patient c'est du bénévolat tout ça après tout.

**Comment by Ricardodel** [comment]
Moi aussi j’ai hâte, mercide l’info

Envoyé de mon iPhone

Le 8 févr. 2023 à 22:02, flingflang ***@***.***> a écrit :

﻿

De mon côté il y a eu progression. Dans les dernières mise à jour Ubuntu, il y avait : kodi-inputstream-adaptive-6:20.3.2-1-focal.amd64. Je l'ai installé et là la video fonctionne. Par contre moi non plus je n'ai pas de son... En fait, j'en ai eu quelques secondes. J'ai lancé une video, je suis allé dans le menu (clavier : M) > Setting > Audio settings > Audio Stream. J'ai basculé le 2/2 vers 1/2 et là j'ai entendu la video description. J'ai rebasculé vers 2/2 : pas de son. Je suis revenu vers 1/2 : plus de son!? Depuis rien. J'ai pas de son peu importe. Mais la video fonctionne toujours.

fait mon petit truc dit plus haut et tu auras du son et si tu as du son et que l'image gèle même petit truc , j ai hâte d'avoir une correction pour ce bug

Et bien ça semble bien fonctionner en effet ton petit truc. J'avais pas porté attention à ton message considérant que je n'avais pas de video du tout..! La victoire est proche. Soyons patient c'est du bénévolat tout ça après tout.

**Comment by KodiTopQuebec** [comment]
il y a eu une mise a jour de inputstream Adaptive version 20.3.3 et tout a l'air ok pour ici tou.tv

**Comment by Ricardodel** [comment]
Merci de l'info, je vais mettre à jour

Envoyé de mon iPad

Le 9 févr. 2023 à 10:35, KodiTopQuebec ***@***.***> a écrit :

﻿

il y a eu une mise a jour de inputstream Adaptive version 20.3.3 et tout a l'air ok pour ici tou.tv

**Comment by flingflang** [comment]
Je confirme ce qu'écrit @KodiTopQuebec  (correction). Ubuntu m'a proposé cette mise à jour aujourd'hui : 
kodi-inputstream-adaptive-6:20.3.3-1~focal.amd64  
Tout fonctionne parfaitement depuis pour tou.tv. Ne pas oublier de redémarrer Kodi. Fin du dossier. Merci!
