### ISSUE TITLE
Noovo problème 

### ISSUE THREAD

**Issue by erikatremblay** [anisite/DepotQuebec#88]
Noovo j’ai un bug avec kodi 19.5. L’émission commence et après 1 sec sa fait comme cesser de jouer.. Je n’ai que du son au début et pas d’image. De plus l’émission est très très lente à ouvrir..

**Comment by anisite** [comment]
Bonjour, avec si peu de détails c'est pas simple, il faut connaitre l'OS et la machine au minimum. Est-ce que d'autres addons ont des problèmes similaires, c'est probablement lié à une accélération matérielle qui ne fonctionne pas correctement ? Il faudrait extraire les logs, pour ma part Kodi 19.3 sur Windows 11 ça fonctionne sans aucun délai ni lag sur l'amour est dans le pré saison 10

Edit: je viens de migrer à Kodi 19.5, tout est beau sur Windows aussi

**Comment by erikatremblay** [comment]
J’ai une beelink GT King Pro - aucune autre application a cette problématique mise à part noovo. 
Tout fonctionne #1 sauf l’application noovo 🤔 je me demande si se ne serait pas les changements apporter dans les codes sources de noovo du printemps 2022 qui ferait cela quand les émissions ne décollaient pu avec kodi 18. Je vais aller effacer le fichier dans mon kodi de noovo et je vais réinstaller des fois 🤷🏼‍♀️ car mon kodi a migrer toutes mes anciennes applications quand j’ai installé kodi 19.5

**Comment by erikatremblay** [comment]
Finalement sa fonctionne pas je vous envoie mon log
[kodi.log](https://github.com/anisite/DepotQuebec/files/10502361/kodi.log)

**Comment by erikatremblay** [comment]
Finalement mon tou.tv fait la même chose 🤔 je comprends pas car tva+ sa fonctionne #1 mais pas noovo ni tou.tv

**Comment by anisite** [comment]
Est-ce pas mal d'ouvrage de faire un fresh install de Kodi 19? C'est étrange mais on dirait un problème de codec. Il y a une erreur avec widevine. Tu pourrais essayer de réinstaller widewine mais je ne sais plus comment forcer je crois via l'addon inputstream helper.

**Comment by erikatremblay** [comment]
Ok m’a essayé tentot

**Comment by erikatremblay** [comment]
Bon j’ai pas mal tout essayé et sans succès j’ai même installé kodi sur une boite beelink GT King avec rien dans kodi sauf le repo de dépôt Québec et sa ne veut toujours pas fonctionner j’ai le même message dans inputstream helper install widevine from: https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_14092.77.0_veyron-fievel_recovery_stable-channel_fievel-mp.bin.zip

je ne comprends pas le kodi est vierge et ce que j’avais lu sur internet était un fichier IOS qui bloquerait mais là c’est impossible. 🤦‍♀️ 
![8490937F-87CB-49E0-AD62-7A3F703F6EC8](https://user-images.githubusercontent.com/43388286/214875533-c71e6ffa-9222-4f96-9a57-59570880bb08.jpeg)

**Comment by anisite** [comment]
Quel message vous avez? Erreur de certificat?

Il faut s'assurer que le fuseau horaire et la date/ heure sont bonnes, 

Aussi, est-ce bien Kodi 64bits? Je crois que le 32 bits n'existe plus de toute façon sur Kodi 19

**Comment by erikatremblay** [comment]
Je crois qu’il existe le 32bits je viens de voir la version kodi 19.5 matrix-armeabi- v7a je vais installer cette version et voir si sa fonctionne

**Comment by erikatremblay** [comment]
Bon nouveau test fait sur une boite beelink GT King wifi 6. La boite est a l’état neuf donc jamais rien eut dessus avant aujourd’hui. 😅 

j’ai installé kodi 19.5 matrix-armeabi-v7a directement sur la page mirrors.kodi.tv

j’ai ouvert kodi laissez les mises à jour de bases se faire ensuite j’ai mit french et canada. L’heure et la date sont bonnes. 

J’ai ensuite installée le repo dépôt Quebec que j’ai prit le fichier zip ici sur github. 

J’ai installé noovo, tou.tv, TVA+ 

j’ai encore le même problème. Je ne reçois aucun message sa ouvre pour noovo, mais pas d’images ni de sons. 

J’avais eut par le passé le même soucis avec disney+ et eux m’avaient dit de mettre sur leur application (sluguy common) le widevine level sur L3 et sa fonctionnait après. 

Mais ce que je ne comprends pas, c’est que c’était les mêmes settings quand j’ai migrer il y a deux jours de kodi 18.9 a kodi 19.5 et mes applications avaient migrer aussi donc cette application de slyguy common, je l’avais avec le setting qu’eux m’avaient dit de mettre et sa fonctionnait dans kodi 18.9, mais pas kodi 19.5. Donc le soucis n’était pas ma programmation. Car dans un kodi vierge j’ai le même problème et le même message qui dit d’installer widevine from…😅🤔 Je vais remettre le log ici des fois 🤷🏼‍♀️

**Comment by erikatremblay** [comment]
[kodi.log.zip](https://github.com/anisite/DepotQuebec/files/10511993/kodi.log.zip)

**Comment by erikatremblay** [comment]
Bon j’ai réussi à les faire fonctionner! 

Pour le moment en réinstallant disney+ et netflix, malheureusement, je ne sais pas lequel des deux m'a aider à faire fonctionner novoo et tou.tv. (j’aurais du y aller un par un, mais bon!)

Je vous explique aussi que netflix a un setting important dans la programmation qui est le ESN / Widevine settings. Car pour certaines boites android la résolution est restreinte. Donc lorsqu'un vidéo de plus de 480p veut ouvrir la boite le bloque. Bref, grace aux add-ons services de slyguy et du plugin.video.netflix il est possible de forcer a jouer les vidéos. :) en mettant le Widevine sur L3. Cela m'a prit plus de 24hrs à régler même si avant j'avais la même programmation lors de la migration, quelque chose n'a surement pas suivi. 

Merci de votre aide. :)
