### ISSUE TITLE
repo Depotquebec

### ISSUE THREAD

**Issue by johnboisvert** [anisite/DepotQuebec#89]
Je n'arrive pas a installer via .zip
c'est quoi le url svp du repo

**Comment by anisite** [comment]
Normalement l'URL est sur le site première page https://github.com/anisite/DepotQuebec/blob/master/repository.depot.quebec/repository.depot.quebec-1.6.1.zip?raw=true

Notez que le dépôt utilise le nouveau format compatible avec Kodi 19 et 20.

**Comment by anisite** [comment]
Pas de nouvelles
