### ISSUE TITLE
probleme avec tou.tv

### ISSUE THREAD

**Issue by stefmeti** [anisite/DepotQuebec#9]
bonjour,

J,ai un problème avec tou,tv depuis le début de la nouvelle saison de radio-canada je ne sais pas pourquoi mais nous avons plus accès a des émissions comme district 31 et unité 9 pourtant l'an passe tout fonctionnait tres bien car ma conjointe a regarder tout les épisodes des 2 émissions sur tou.tv sur kodi.

ma version de tou.tv est la suivante 2.0.4
et je suis un android box

Merci beaucoup pour votre aide

**Comment by anisite** [comment]
Je vais regarder ça demain soir, tenter de trouver une solution.

**Comment by anisite** [comment]
Je viens de pousser l'update 2.0.5, pouvez-vous valider le fonctionnement ou non? Merci.

**Comment by dover19** [comment]
Moi ça reste à 2.0.4

**Comment by dover19** [comment]
Même après avoir fait un update manuel avec le fichier zip ça ne fonctionne quand même pas pour District 31 ou Unité 9.

**Comment by stefmeti** [comment]
Non même après un update manuel ça ne fonctionne toujour pas et j'ai essayer à plusieurs reprise


Envoyé depuis mon téléphone intelligent Samsung Galaxy.-------- Message d'origine --------De : dover19 <notifications@github.com> Date : 2017-09-14  8:30 PM  (GMT-05:00) À : dualB/DepotQuebec <DepotQuebec@noreply.github.com> Cc : stefmeti <stephanemetivier61@gmail.com>, Author <author@noreply.github.com> Objet : Re: [dualB/DepotQuebec] probleme avec tou.tv (#9) 
Même après avoir fait un update manuel avec le fichier zip ça ne fonctionne quand même pas pour District 31 ou Unité 9.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dualB/DepotQuebec","title":"dualB/DepotQuebec","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dualB/DepotQuebec"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dover19 in #9: Même après avoir fait un update manuel avec le fichier zip ça ne fonctionne quand même pas pour District 31 ou Unité 9."}],"action":{"name":"View Issue","url":"https://github.com/dualB/DepotQuebec/issues/9#issuecomment-329644438"}}}

**Comment by stefmeti** [comment]
Je vais essayer dans 5 min merci


Envoyé depuis mon téléphone intelligent Samsung Galaxy.-------- Message d'origine --------De : anisite <notifications@github.com> Date : 2017-09-14  8:21 PM  (GMT-05:00) À : dualB/DepotQuebec <DepotQuebec@noreply.github.com> Cc : stefmeti <stephanemetivier61@gmail.com>, Author <author@noreply.github.com> Objet : Re: [dualB/DepotQuebec] probleme avec tou.tv (#9) 
Je viens de pousser l'update 2.0.5, pouvez-vous valider le fonctionnement ou non? Merci.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dualB/DepotQuebec","title":"dualB/DepotQuebec","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dualB/DepotQuebec"}},"updates":{"snippets":[{"icon":"PERSON","message":"@anisite in #9: Je viens de pousser l'update 2.0.5, pouvez-vous valider le fonctionnement ou non? Merci."}],"action":{"name":"View Issue","url":"https://github.com/dualB/DepotQuebec/issues/9#issuecomment-329643340"}}}

**Comment by stefmeti** [comment]
Je ne vois pas l'update nul part ni dans le repo ni en passant par le ficher zup de libretv et même après avoir redémarrer kodi toujour pas d'un date 2.0.5 de disponible


Envoyé depuis mon téléphone intelligent Samsung Galaxy.-------- Message d'origine --------De : anisite <notifications@github.com> Date : 2017-09-14  8:21 PM  (GMT-05:00) À : dualB/DepotQuebec <DepotQuebec@noreply.github.com> Cc : stefmeti <stephanemetivier61@gmail.com>, Author <author@noreply.github.com> Objet : Re: [dualB/DepotQuebec] probleme avec tou.tv (#9) 
Je viens de pousser l'update 2.0.5, pouvez-vous valider le fonctionnement ou non? Merci.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dualB/DepotQuebec","title":"dualB/DepotQuebec","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dualB/DepotQuebec"}},"updates":{"snippets":[{"icon":"PERSON","message":"@anisite in #9: Je viens de pousser l'update 2.0.5, pouvez-vous valider le fonctionnement ou non? Merci."}],"action":{"name":"View Issue","url":"https://github.com/dualB/DepotQuebec/issues/9#issuecomment-329643340"}}}

**Comment by stefmeti** [comment]
L'update n'est toujour pas disponible


Envoyé depuis mon téléphone intelligent Samsung Galaxy.-------- Message d'origine --------De : anisite <notifications@github.com> Date : 2017-09-14  8:21 PM  (GMT-05:00) À : dualB/DepotQuebec <DepotQuebec@noreply.github.com> Cc : stefmeti <stephanemetivier61@gmail.com>, Author <author@noreply.github.com> Objet : Re: [dualB/DepotQuebec] probleme avec tou.tv (#9) 
Je viens de pousser l'update 2.0.5, pouvez-vous valider le fonctionnement ou non? Merci.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dualB/DepotQuebec","title":"dualB/DepotQuebec","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dualB/DepotQuebec"}},"updates":{"snippets":[{"icon":"PERSON","message":"@anisite in #9: Je viens de pousser l'update 2.0.5, pouvez-vous valider le fonctionnement ou non? Merci."}],"action":{"name":"View Issue","url":"https://github.com/dualB/DepotQuebec/issues/9#issuecomment-329643340"}}}

**Comment by dover19** [comment]
> L'update n'est toujour pas disponible

Si tu download le fichier ZIP et installe a partir du fichier ZIP dans Kodi ca update a 2.0.5. Par contre, pour moi ca ne change absolument rien.

**Comment by stefmeti** [comment]
Après avoir réinstaller tout le dépôt et effacer ma cache à plusieurs reprises je n'est toujour pas la mise à jour à la version 2.0.5


Envoyé depuis mon téléphone intelligent Samsung Galaxy.-------- Message d'origine --------De : anisite <notifications@github.com> Date : 2017-09-14  8:21 PM  (GMT-05:00) À : dualB/DepotQuebec <DepotQuebec@noreply.github.com> Cc : stefmeti <stephanemetivier61@gmail.com>, Author <author@noreply.github.com> Objet : Re: [dualB/DepotQuebec] probleme avec tou.tv (#9) 
Je viens de pousser l'update 2.0.5, pouvez-vous valider le fonctionnement ou non? Merci.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dualB/DepotQuebec","title":"dualB/DepotQuebec","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dualB/DepotQuebec"}},"updates":{"snippets":[{"icon":"PERSON","message":"@anisite in #9: Je viens de pousser l'update 2.0.5, pouvez-vous valider le fonctionnement ou non? Merci."}],"action":{"name":"View Issue","url":"https://github.com/dualB/DepotQuebec/issues/9#issuecomment-329643340"}}}

**Comment by anisite** [comment]
Il est possible que ce soit pas tout le monde qui reçoive rapidement l'update, je vais voir si demain soir c'est ok pour tous, sinon j'investiguerai. Merci!

**Comment by stefmeti** [comment]
Je ne sais pas si tu as reçu mes réponse car je suis avec mon cell mais j'ai toujour pas reçu la mise à jour à la version 2.0.5


Envoyé depuis mon téléphone intelligent Samsung Galaxy.-------- Message d'origine --------De : anisite <notifications@github.com> Date : 2017-09-14  8:21 PM  (GMT-05:00) À : dualB/DepotQuebec <DepotQuebec@noreply.github.com> Cc : stefmeti <stephanemetivier61@gmail.com>, Author <author@noreply.github.com> Objet : Re: [dualB/DepotQuebec] probleme avec tou.tv (#9) 
Je viens de pousser l'update 2.0.5, pouvez-vous valider le fonctionnement ou non? Merci.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dualB/DepotQuebec","title":"dualB/DepotQuebec","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dualB/DepotQuebec"}},"updates":{"snippets":[{"icon":"PERSON","message":"@anisite in #9: Je viens de pousser l'update 2.0.5, pouvez-vous valider le fonctionnement ou non? Merci."}],"action":{"name":"View Issue","url":"https://github.com/dualB/DepotQuebec/issues/9#issuecomment-329643340"}}}

**Comment by stefmeti** [comment]
Un gros merci pour ton temps et ton aide j'apprecie enormement ton dévouement merci beaucoup pour ton super travail


Envoyé depuis mon téléphone intelligent Samsung Galaxy.-------- Message d'origine --------De : anisite <notifications@github.com> Date : 2017-09-14  9:49 PM  (GMT-05:00) À : dualB/DepotQuebec <DepotQuebec@noreply.github.com> Cc : stefmeti <stephanemetivier61@gmail.com>, Author <author@noreply.github.com> Objet : Re: [dualB/DepotQuebec] probleme avec tou.tv (#9) 
Il est possible que ce soit pas tout le monde qui reçoive rapidement l'update, je vais voir si demain soir c'est ok pour tous, sinon j'investiguerai. Merci!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dualB/DepotQuebec","title":"dualB/DepotQuebec","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dualB/DepotQuebec"}},"updates":{"snippets":[{"icon":"PERSON","message":"@anisite in #9: Il est possible que ce soit pas tout le monde qui reçoive rapidement l'update, je vais voir si demain soir c'est ok pour tous, sinon j'investiguerai. Merci!"}],"action":{"name":"View Issue","url":"https://github.com/dualB/DepotQuebec/issues/9#issuecomment-329655191"}}}

**Comment by dover19** [comment]
stefmeti, pourquoi tu ne prends pas le fichier ZIP ici:
https://github.com/dualB/DepotQuebec/blob/master/plugin.infologique.tou.tv/plugin.infologique.tou.tv-2.0.5.zip

Voici des instructions pour installer a partir d'un fichier zip:
http://kodi.wiki/view/HOW-TO:Install_add-ons_from_zip_files

**Comment by stefmeti** [comment]
Merci


Envoyé depuis mon téléphone intelligent Samsung Galaxy.-------- Message d'origine --------De : dover19 <notifications@github.com> Date : 2017-09-14  10:24 PM  (GMT-05:00) À : dualB/DepotQuebec <DepotQuebec@noreply.github.com> Cc : stefmeti <stephanemetivier61@gmail.com>, Author <author@noreply.github.com> Objet : Re: [dualB/DepotQuebec] probleme avec tou.tv (#9) 
stefmeti, pourquoi tu ne prends pas le fichier ZIP ici:

https://github.com/dualB/DepotQuebec/blob/master/plugin.infologique.tou.tv/plugin.infologique.tou.tv-2.0.5.zip
Voici des instructions pour installer a partir d'un fichier zip:

http://kodi.wiki/view/HOW-TO:Install_add-ons_from_zip_files

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dualB/DepotQuebec","title":"dualB/DepotQuebec","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dualB/DepotQuebec"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dover19 in #9: stefmeti, pourquoi tu ne prends pas le fichier ZIP ici:\r\nhttps://github.com/dualB/DepotQuebec/blob/master/plugin.infologique.tou.tv/plugin.infologique.tou.tv-2.0.5.zip\r\n\r\nVoici des instructions pour installer a partir d'un fichier zip:\r\nhttp://kodi.wiki/view/HOW-TO:Install_add-ons_from_zip_files"}],"action":{"name":"View Issue","url":"https://github.com/dualB/DepotQuebec/issues/9#issuecomment-329660636"}}}

**Comment by anisite** [comment]
Bonjour, j'ai travaillé jusqu'aux petites heures cette nuit, la version 2.0.6 devrait fonctionner tant sur windows que sur android.

**Comment by TechnoPhysCAL** [comment]
:+1: Good job!
Si c'est possible, quand tu fais un commit, mon script refait les calculs de md5 pour l'ensemble des fichiers... essaie d'exclure ces fichiers (ignore changes), sinon l'ensemble des fichiers du dépôt se retrouvent à être inclus dans un commit qui ne les concernent pas. 
Faudrait que j'améliore ça d'ici là..

**Comment by dualB** [comment]
:+1: Good job!
Si c'est possible, quand tu fais un commit, mon script refait les calculs de md5 pour l'ensemble des fichiers... essaie d'exclure ces fichiers (ignore changes), sinon l'ensemble des fichiers du dépôt se retrouvent à être inclus dans un commit qui ne les concernent pas.
Faudrait que j'améliore ça d'ici là..

**Comment by dover19** [comment]
Good job, ca fonctionne pour moi aussi sur linux (LibreElec). Merci beaucou! :)

**Comment by anisite** [comment]
@dualB J'ai ajusté le calcul du MD5 pour qu'il génère le bon MD5 (avant il était différent sur linux vs windows) cette fois-ci les md5 devraient être identiques, donc git ne devrait plus les mettre en "changes" à voir... j'ai aussi lu que le MD5 ne sert pas à valider le .zip, kodi s,en sert juste pour savoir si le .xml a changé... (donc plus ou moins important...) bref, je vais faire attention!

@stefmeti c'est bon de ton côté?

**Comment by dualB** [comment]
On a la meilleure équipe :)

**Comment by stefmeti** [comment]
Merci beaucoup anisite pour ton travail tout fonctionne bien chez moi également j'apprecie ton dévouement encore une merci beaucoup


Envoyé depuis mon téléphone intelligent Samsung Galaxy.-------- Message d'origine --------De : anisite <notifications@github.com> Date : 2017-09-15  1:19 PM  (GMT-05:00) À : dualB/DepotQuebec <DepotQuebec@noreply.github.com> Cc : stefmeti <stephanemetivier61@gmail.com>, Mention <mention@noreply.github.com> Objet : Re: [dualB/DepotQuebec] probleme avec tou.tv (#9) 
@dualB J'ai ajusté le calcul du MD5 pour qu'il génère le bon MD5 (avant il était différent sur linux vs windows) cette fois-ci les md5 devraient être identiques, donc git ne devrait plus les mettre en "changes" à voir... j'ai aussi lu que le MD5 ne sert pas à valider le .zip, kodi s,en sert juste pour savoir si le .xml a changé... (donc plus ou moins important...) bref, je vais faire attention!
@stefmeti c'est bon de ton côté?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dualB/DepotQuebec","title":"dualB/DepotQuebec","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dualB/DepotQuebec"}},"updates":{"snippets":[{"icon":"PERSON","message":"@anisite in #9: @dualB J'ai ajusté le calcul du MD5 pour qu'il génère le bon MD5 (avant il était différent sur linux vs windows) cette fois-ci les md5 devraient être identiques, donc git ne devrait plus les mettre en \"changes\" à voir... j'ai aussi lu que le MD5 ne sert pas à valider le .zip, kodi s,en sert juste pour savoir si le .xml a changé... (donc plus ou moins important...) bref, je vais faire attention!\r\n\r\n@stefmeti c'est bon de ton côté?"}],"action":{"name":"View Issue","url":"https://github.com/dualB/DepotQuebec/issues/9#issuecomment-329844515"}}}

**Comment by anisite** [comment]
Merci de votre patience, j'ai pas toujours beaucoup de temps!
