### ISSUE TITLE
ici tou.tv kodi 20

### ISSUE THREAD

**Issue by KodiTopQuebec** [anisite/DepotQuebec#90]
depuis hier ici tou.tv ne fonctionne plus sous kodi 20 , je n'ai pas essayé par contre sous kodi 19, lorsque l'on clique sur le addon il y a un message erreur et rien ne s'affiche , est ce qu'il y a un dev qui voudrait bien faire la correction merci beaucoup de votre travail c'est très apprécié

**Comment by anisite** [comment]
Je viens de vérifier et ça fonctionne très bien de mon côté, est-ce avec un compte Extra ? Est-ce possible d'avoir un log ?

**Comment by anisite** [comment]
Kodi 20 sur Windows 11 fonctionne très bien avec ou sans compte Extra de mon côté

**Comment by KodiTopQuebec** [comment]
je suis tellement désolé de t'avoir dérangé avec un problème d'ici , comme tu dis cela venait de mon compte extra qui était expiré , je me sens tellement (cave) de ne pas y avoir pensé , merci de ton soutien c'est très apprécié

**Comment by anisite** [comment]
Bah ça aurait été plus simple aussi si tu avait eu une message plus clair mais bon c'est pas simple de gère tous les cas d'erreurs. Merci
