### ISSUE TITLE
ici tou.tv

### ISSUE THREAD

**Issue by KodiTopQuebec** [anisite/DepotQuebec#93]
depuis 2 jours ici tou.tv ne se met pas a jour pour le ratrappage

sur toute les plateformes , ( android et pc)

**Comment by captzapo** [comment]
J'ai le même problème de mon côté, mais ça ne semble pas se limiter à la section rattrapage. Tout contenu normalement disponible sur le site après le 17 octobre n'apparait pas dans les listes. 

Il est toujours possible de lire les vidéos antérieurs à cette date. 

Ceci pourrait être dü à une refonte récente du site ou simplement une panne empêchant la mise à jour du côté API. 

J'ai tenté de réinstaller le plugin, vider le cache, etc sans succès.

Je profite de l'occasion pour remercier tout ceux qui ont donné de leur temps jusqu'à maintenant à ce projet.

**Comment by captzapo** [comment]
Il semblerait que la cause du problème était un problème de mise à jour du côté du site même.

Tout est rentré dans l''ordre pour moi aujourd'hui, Toutes les listes se mettent à jour correctement,

**Comment by KodiTopQuebec** [comment]
@captzapo merci de l'info effectivement tout est parfait ici aussi
