### ISSUE TITLE
Kodi 21.0 (inputstream.adaptative)

### ISSUE THREAD

**Issue by BassLortie** [anisite/DepotQuebec#97]
Les addon ne fonctionnent plus à cause de la nouvelle version de Kodi qui ne supporte pas inputstream.adaptative...

**Comment by anisite** [comment]
Salut, pourquoi dis-tu que Kodi 21 ne supporte plus input stream.adaptative?

![Screenshot_20240426-183207.png](https://github.com/anisite/DepotQuebec/assets/3194288/206a58c9-d65a-451d-92d0-afdc119b9852)

Kodi 21 sur Android avec input stream tou.tv fonctionne ici.

**Comment by BassLortie** [comment]
En effet, je viens de constater que ma version de inputstream.adaptative était pas à jour... Je viens de re tester après mise à jour et c'est ok
