### ISSUE TITLE
Tva non fonctionnel

### ISSUE THREAD

**Issue by erikatremblay** [anisite/DepotQuebec#98]
J’ai kodi 20.5 et TVA ne fonctionne plus du tout si quelqu’un peut aider sa serait bien! Merci

**Comment by boucchar** [comment]
Bonjour, je constate la même chose ici. TVA ne load plus du tout. Merci encore de votre travail. On s'en sert full pin ici :)

**Comment by BassLortie** [comment]
Pareil pour moi tva plante à l'ouverture autant sur pc, téléphone android et android tv...

**Comment by KodiTopQuebec** [comment]
Toujours rien sur ce problème  ? , @anisite

**Comment by Michaeld506** [comment]
Pareil pour moi

**Comment by koddyhack** [comment]
Moi aussi il crash à l’ouverture de l’extension 
J’ai essayé aussi les anciennes versions 
Merci de vérifier @anisite 
On adore vos applications pour nous les québécois!

**Comment by anisite** [comment]
Je peux regarder dès que j'ai un moment mais ça risque d'être juste samedi prochain

**Comment by anisite** [comment]
https://github.com/anisite/plugin.infologique.TVAgo/issues/29#issuecomment-2345216949

**Comment by KodiTopQuebec** [comment]
@anisite toujours rien sur la correction ?

**Comment by erikatremblay** [comment]
Est-ce possible que quelqu’un aide car moi j’adore ses applications dans kodi 😭😭😭

**Comment by antoyo** [comment]
> Est-ce possible que quelqu’un aide car moi j’adore ses applications dans kodi 😭😭😭

Je pourrais peut-être faire un patch, mais quand j'avais regardé, je n'étais pas sûr de comment lister les émissions via l'API: de ce que j'ai vu, j'ai l'impression que les émissions étaient peut-être listé dans l'array `associatedEntities` de la réponse JSON (vu que le code utilise cet array), mais l'API retourne maintenant un array vide pour ce champ.

Donc, si quelqu'un pouvait me guider un peu pour savoir comment trouver les URLs d'API à appeler, je pourrais possiblement corriger le problème.

**Edit:** Oh, avec le header mentionné [là](https://github.com/anisite/plugin.infologique.TVAgo/issues/29#issuecomment-2345216949), ça semble retourner les émissions. Je regarde pour patcher le code.

**Comment by antoyo** [comment]
@erikatremblay: j'ai partiellement corrigé le problème en ajoutant cette ligne:
```python
    req.add_header('x-pfu-tenant', 'TVAPLUS')
```
après [cette ligne](https://github.com/anisite/plugin.infologique.TVAgo/blob/master/resources/lib/html.py#L73).

Je peux à nouveau regarder des émissions, mais ça ne semble fonctionner que parce que j'avais mis en favoris l'émission TVA. La liste d'émission est toujours brisée.

Comme ce fix n'est pas complet, je présume que ça ne sert à rien d'envoyer une PR.
Et comme ça fonctionne pour moi et que je n'ai pas vraiment de temps à mettre là-dessus, je ne continuerai pas à investiguer.
J'espère que ça aide.

**Comment by erikatremblay** [comment]
@antoyo merci mais moi je n’ai rien en favoris donc sa ne fonctionnera pas pour moi!

**Comment by anisite** [comment]
je vais tenter de débug ça demain, est-ce que quelqu'un réussi à corriger les émissions non mis en favoris ?

**Comment by anisite** [comment]
> Pareil pour moi tva plante à l'ouverture autant sur pc, téléphone android et android tv...

@BassLortie  c'est toujours le cas ?

**Comment by BassLortie** [comment]
> > Pareil pour moi tva plante à l'ouverture autant sur pc, téléphone android et android tv...
> 
> @BassLortie c'est toujours le cas ?

TVA ouvre mais rien n'est affiché aucun contenu trouvé

**Comment by erikatremblay** [comment]
Oui toujours non fonctionnel il ouvre mais rien dans la liste

**Comment by anisite** [comment]
> Oui toujours non fonctionnel il ouvre mais rien dans la liste 

@erikatremblay et @BassLortie pouvez vous tester la version 3.0.0? Merci

**Comment by PolatQc** [comment]
nice, c'est fonctionnel.

Il y a une petite erreur ( sous kodi 21) causer par la ligne 149 dans default.py. 
    PATH = translatePath('special://temp').decode('utf-8')

**Comment by anisite** [comment]
Ça fait planter? J'ai pas vu cette erreur va falloir je regarde

**Comment by PolatQc** [comment]
> Ça fait planter? J'ai pas vu cette erreur va falloir je regarde

non, ça ne plante pas, ca fait juste dire qu'il y a une erreur et on la voit dans le log. 

 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'decode'
                                                   Traceback (most recent call last):
                                                     File "\AppData\Roaming\Kodi\addons\plugin.infologique.TVAgo\default.py", line 149, in <module>
                                                       PATH = translatePath('special://temp').decode('utf-8')
                                                   AttributeError: 'str' object has no attribute 'decode'
                                                   -->End of Python script error report<--

**Comment by BassLortie** [comment]
> > Oui toujours non fonctionnel il ouvre mais rien dans la liste
> 
> @erikatremblay et @BassLortie pouvez vous tester la version 3.0.0? Merci

Je viens de tester et ça semble correct

**Comment by erikatremblay** [comment]
Je ne vois pas de version 3.0.0 je suis a la version 2.0.7 et je n’ai pas de mise à jour j’ai vérifier, redémarrer et pas de version 3.0.0 🤷🏼‍♀️

**Comment by erikatremblay** [comment]
Ok sa fonctionne! :)

**Comment by erikatremblay** [comment]
Merci infiniment

**Comment by anisite** [comment]
De rien désolé du délai, j'ai été très occupé puis jai eu un mini accident, rien de grave mais bon, pas la joie ;-)

**Comment by erikatremblay** [comment]
Merci énormément 🙏🏻 et prenez soin de vous!

**Comment by PolatQc** [comment]
J'ai modifier un peu l'addon avec l'aide de IA (Gemini) pour avoir la page qui contient le contenu de A à Z sur la première page. Ils manquaient pas mal de contenu.  Si jamais tu veux voir/ajouter ça Anisite

**Comment by erikatremblay** [comment]
Malheureusement, il manque plusieurs émissions à TVA actuellement. Il n’y en a que 31 il y en avait beaucoup plus que cela avant.
